/**
 * Regenerate the embedded definition-of-done from its source document.
 *
 * `docs/DONE-CHECKLIST.md` is the single source of truth and the orchestrator
 * parses it directly. This generator runs in the browser and cannot read files
 * at generate time, so the rows are embedded in
 * `src/lib/prd/sections/doneChecklist.ts`.
 *
 * The embedded copy is only safe because `doneChecklist.test.ts` re-parses the
 * real document and fails when the two disagree. Run this after editing the
 * checklist.
 *
 * Usage: npx tsx scripts/regen-done-checklist.mts
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadChecklistRows } from '../../orchestrator/src/done/checklist.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, '../..');
const checklistPath = join(repoRoot, 'docs/DONE-CHECKLIST.md');
const outPath = join(here, '../src/lib/prd/sections/doneChecklist.ts');

interface Row {
  id: string;
  section: string;
  sectionTitle: string;
  mustBeTrue: string;
  evidence: string;
}

const rows = loadChecklistRows(checklistPath) as Row[];
const sections = new Map<string, { title: string; rows: Row[] }>();
for (const row of rows) {
  const existing = sections.get(row.section);
  if (existing) existing.rows.push(row);
  else sections.set(row.section, { title: row.sectionTitle, rows: [row] });
}

const q = (value: string): string => JSON.stringify(value);

const entries = [...sections.entries()]
  .map(([letter, section]) => {
    const rowLines = section.rows
      .map(
        (r) =>
          `      { id: ${q(r.id)}, mustBeTrue: ${q(r.mustBeTrue)}, evidence: ${q(r.evidence)} }`
      )
      .join(',\n');
    return `  {\n    letter: ${q(letter)},\n    title: ${q(section.title)},\n    rows: [\n${rowLines}\n    ]\n  }`;
  })
  .join(',\n');

const file = `/**
 * The definition of done, embedded for the PRD generator.
 *
 * WHY EMBEDDED RATHER THAN READ
 * -----------------------------
 * \`docs/DONE-CHECKLIST.md\` is the single source of truth and the orchestrator
 * parses it directly. This generator runs in the browser, so it cannot read that
 * file at generate time. The rows are therefore embedded here, and
 * \`doneChecklist.test.ts\` re-parses the real document and fails when this copy
 * has drifted. That test is the only thing that makes an embedded duplicate
 * safe -- do not delete it.
 *
 * Generated by \`npx tsx scripts/regen-done-checklist.mts\`. Edit the document,
 * not this file.
 */

export interface ChecklistRow {
  readonly id: string;
  readonly mustBeTrue: string;
  readonly evidence: string;
}

export interface ChecklistSection {
  readonly letter: string;
  readonly title: string;
  readonly rows: readonly ChecklistRow[];
}

export const DONE_CHECKLIST_SECTIONS: readonly ChecklistSection[] = [
${entries}
];

/** Heading the self-check looks for to prove the block was emitted. */
export const DEFINITION_OF_DONE_HEADING = '### Definition of Done (non-optional)';

/**
 * Render the definition of done for inclusion in a generated PRD.
 *
 * Emitted into every PRD so a builder is handed all of the finish-line
 * conditions up front instead of discovering them one gate failure at a time.
 * \`selfCheck\` fails any PRD that does not contain it.
 *
 * @returns Markdown for the Definition of Done block.
 */
export function buildDefinitionOfDone(): string {
  const lines: string[] = [
    DEFINITION_OF_DONE_HEADING,
    '',
    'Nothing may be called done, finished, shipped, complete, or working until every',
    'row below has been **measured** and its **evidence artifact opened**. A spec, a',
    'prompt, a plan, or a rule file is never evidence, and neither is an agent',
    'summarising its own work. The gate evaluates every row and fail-closes on any row',
    'that is unmeasured or has no implementation behind it.',
    ''
  ];
  for (const section of DONE_CHECKLIST_SECTIONS) {
    lines.push(\`**\${section.letter}. \${section.title}**\`, '');
    for (const row of section.rows) {
      const evidence = row.evidence === '' ? '' : \` — evidence: \${row.evidence}\`;
      lines.push(\`- [ ] **\${row.id}** — \${row.mustBeTrue}\${evidence}\`);
    }
    lines.push('');
  }
  return lines.join('\\n').trimEnd() + '\\n';
}
`;

writeFileSync(outPath, file);
process.stdout.write(`wrote ${rows.length} rows across ${sections.size} sections to ${outPath}\n`);
