#!/usr/bin/env node
/**
 * The `product` role: distil the generated PRD into a product brief.
 *
 * Deliberately derived from the PRD rather than written fresh. A brief authored
 * beside the PRD is a second opinion that quietly competes with it; the point of
 * this step is to state, in one page, who the app is for and the single flow
 * that must work, so the build has one thing to optimise instead of a rubric.
 *
 * Extraction only -- it does not invent. If the PRD lacks a section, that shows
 * as a gap in the brief rather than being filled in with plausible prose.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const args = Object.fromEntries(
  process.argv.slice(2).flatMap((a) => {
    const m = /^--([^=]+)=([\s\S]*)$/.exec(a);
    return m ? [[m[1], m[2]]] : [];
  })
);
if (!args.slug) {
  process.stderr.write('usage: product.mjs --slug=X [--repoRoot=.]\n');
  process.exit(2);
}
const appDir = join(resolve(args.repoRoot ?? process.cwd()), args.slug);
const prdPath = join(appDir, 'docs', 'PRD.md');
if (!existsSync(prdPath)) {
  process.stderr.write(`no PRD at ${prdPath} -- the product role cannot precede the prd role\n`);
  process.exit(1);
}
const prd = readFileSync(prdPath, 'utf8');

/**
 * Pull a numbered section out of the PRD by heading text.
 * @param {string} title heading to find, case-insensitive
 * @param {number} maxChars cap so the brief stays a brief
 * @returns {string} the section body, or an explicit gap marker
 */
function section(title, maxChars = 1400) {
  // No `m` flag. With it, `$` means end of LINE, so the lazy body matched the
  // empty string immediately and every section came back blank -- the brief was
  // 663 bytes of headings. Heading depth goes to 4 because the PRD puts
  // "7.3a Design direction" at #### depth.
  const re = new RegExp(
    `(?:^|\\n)#{1,4}[ \\t]*(?:\\d+(?:\\.\\d+)*[a-z]?\\.?[ \\t]*)?${title}[^\\n]*\\n([\\s\\S]*?)(?=\\n#{1,4}[ \\t]|$(?![\\s\\S]))`,
    'i'
  );
  const m = re.exec(prd);
  if (!m || !m[1].trim()) {
    return `_The PRD has no "${title}" section with content. Recorded as a gap rather than invented._`;
  }
  return m[1].trim().slice(0, maxChars);
}

const brief = `# Product brief — ${args.slug}

Derived from \`docs/PRD.md\` by \`roles/product.mjs\`. Extraction only: nothing here
is invented, and a section the PRD does not contain is recorded as a gap rather
than filled in with plausible prose.

## Who it is for and the problem

${section('Problem Statement')}

## What it does

${section('Solution Overview')}

## The one flow that must work

${section('User Stories', 1800)}

## What success looks like

${section('Success Outcome')}

## Explicitly out of scope

${section('Non-goals')}

## Design direction — binding

${section('Design direction', 1200)}

---

Source: \`docs/PRD.md\` (${prd.length} chars), generated by the deployed RedAnvil
app-builder. See \`docs/prd-provenance.json\` for the wizard answers that produced it.
`;

mkdirSync(join(appDir, 'docs'), { recursive: true });
writeFileSync(join(appDir, 'docs', 'PRODUCT-BRIEF.md'), brief);
console.log(`product brief written: ${brief.length} chars from a ${prd.length}-char PRD`);
