-- Seed one real PRD so /api/prd/[id] has a demonstrable success path.
--
-- Why: u-api-real-output found that the PRD detail endpoint could not be shown
-- to return real data, because nothing ever created a PRD row. The route
-- answered 404 correctly and forever -- an endpoint no data could exercise,
-- which is a gap the gate is supposed to surface rather than a rule to waive.
--
-- PROVENANCE: this is NOT hand-authored. Every field is copied verbatim from
-- src/lib/prd.characterization.fixtures/dashboard-auth-two-entities.json, which
-- is a recorded output of this app's own PRD generator and is asserted against
-- by the characterization tests. Seeding the generator's real output means the
-- detail endpoint serves exactly what the product produces, not a stand-in
-- shaped like it.
--
-- created_at is fixed, not now(): a migration that stamps the current time
-- produces a different database on every run and makes the row untestable.

INSERT OR IGNORE INTO prds (id, slug, title, prompt, markdown, created_at) VALUES (
  'prd-tesla-driving-stats',
  'build-an-app-for-tracking-tesla-driving-stats',
  'Build an app for Tracking Tesla Driving Stats',
  'Build an app for tracking tesla driving stats',
  '# Implementation Spec — Build an app for Tracking Tesla Driving Stats

```yaml
appType: "dashboard"
hasAuth: true
entities: ["trips", "drivers"]
targetType: fullstack-web
threshold: 90
slug: "build-an-app-for-tracking-tesla-driving-stats"
title: "Build an app for Tracking Tesla Driving Stats"
```

> Generated by RedAnvil App Builder. Paste this whole document into Claude (or Grok) to build the app. Threshold to ship: **score >= 90** on the RedAnvil rubric.

## 1. Introduction

**Build an app for Tracking Tesla Driving Stats** is a **dashboard** that addresses: Build an app for tracking tesla driving stats. It ships as a full-stack Cloudflare app (Pages + Pages Functions + D1) with gate threshold **90**. MVP scope is F1, F2, F3, F4; ship those vertical slices before Beyond-MVP work.

## 2. Problem Statement

Build an app for tracking tesla driving stats

Users lack a single, reliable place to track and act on the domain above. The cost of missing a due item is real-world failure (missed care, lost data, or repeated manual chase). This app exists so that the stated need is handled end-to-end in software, not spreadsheets or memory.

## 3. Solution Overview

The app solves the problem with a dashboard built on Cloudflare Pages (Vite + React + TypeScript SPA), Pages Functions for the API, and Cloudflare D1 for persistence (Simple D1 tables (CRUD + parameterized queries)). Domain entities in scope: **Trip, Driver**. Authentication uses Web Crypto only (PBKDF2 + HMAC session cookies); all domain rows are scoped to the signed-in user. Users complete MVP flows (F1, F2, F3, F4) first: browse and manage the primary entity, open detail, and sign in. Each capability is delivered as a vertical slice (DB + API + UI + tests) so something works end-to-end after every slice, not only at the end of a horizontal phase plan.

## 4. Success Outcome

Definition of done — observable, checkable statements (not aspirations):

- A user can complete the MVP flows (F1, F2, F3, F4) without auth walls unless auth is in scope.
- Every MVP acceptance bullet under §9 is exercised by a named test in §10 and is green.
- `GET /api/health` returns JSON including `"status":"ok"` on a local Pages Functions serve.
- `npx tsc --noEmit`, `npx eslint . --max-warnings 0`, `npx vitest run`, and `npm run build` all exit 0.
- From monorepo root, `npm run gate -- build-an-app-for-tracking-tesla-driving-stats --threshold 90` reports score >= **90** with zero tier-1 blockers.
- No incomplete stub copy remains in the product UI; all user-facing strings live in `src/i18n/en.ts`.
- The product named **Build an app for Tracking Tesla Driving Stats** solves the problem stated in §2 for the MVP feature set alone.

## 5. Non-goals / Out of scope

- Do not invent domain entities beyond the frontmatter list: **Trip, Driver**.
- Auth is in scope (Web Crypto only). Do not add OAuth, social login, or third-party IdPs unless the mission states them.
- No payment processing, billing, or third-party integrations unless the mission names them (no Stripe, no vault, no secret files in the repo).
- No deploy automation inside the app itself (no CI push-to-prod buttons, no wrangler deploy from client code).
- **Single-tenant** — no multi-org, team workspaces, or tenant isolation layers.
- No Supabase, Express, bcrypt, or jsonwebtoken (Workers-incompatible).
- No Node-only globals (`process`, `Buffer`) or native modules (`better-sqlite3`) in Worker/browser code.
- No native mobile shell — full-stack web (Cloudflare Pages) only.

## 6. User Stories

- As a **registered user**, I want **browse & search Trip**, so that **Users can open the trips list, search by title, and see matching rows or an empty state**.
- As a **registered user**, I want **trip detail**, so that **Clicking a list row opens the full Trip record with title, description, and a back link**.
- As a **registered user**, I want **accounts**, so that **Register and sign in with Web Crypto (PBKDF2 + HMAC-SHA256 sessions); data is scoped to the signed-in user**.
- As a **registered user**, I want **manage Trip**, so that **Create, edit, and delete trips with confirmation before delete**.
- As a **builder**, I want **a vertical-slice build plan with verify commands**, so that **Build an app for tracking tesla driving stats** can be shipped with continuous end-to-end feedback.

## 7. Technical Requirements

### 7.1 Architecture

Concrete runtime for a coding agent that has **only this PRD**.

### Stack

| Layer | Choice |
|-------|--------|
| UI | Vite + React + TypeScript (strict) SPA on **Cloudflare Pages** |
| API | **Cloudflare Pages Functions** (`functions/api/*`) |
| Data | **Cloudflare D1** — Simple D1 tables (CRUD + parameterized queries) |
| Auth | Web Crypto (PBKDF2 password hash + HMAC-SHA256 session cookies) in Pages Functions |
| Realtime | No — request/response only; do not add sockets or live channels. |
| Integrations | None specified — do not invent third-party integrations. |

### Request flow

```
Browser (SPA)
   |  fetch /api/...
   v
Pages Function  -- Zod validate at boundary
   |  parameterized SQL only
   v
D1 binding (env.DB)
   |
   v
JSON Response + security headers (from shared http helper)
```

### Where concerns live

- **Validation:** Zod schemas in `src/lib` / `functions` at every request boundary; fail closed (400) on invalid input.
- **Error handling:** typed errors; never swallow exceptions; never render failure as an empty success.
- **Security headers / CORS:** shared helper in `functions/lib/http.ts` (or equivalent) applied on every API response.
- **Secrets:** Cloudflare secrets / `.env` only — never in source, client bundles, or logs.

### Layer boundaries (hard)

- No Node-only globals (`process`, `Buffer`) or native modules (`better-sqlite3`, `bcrypt`, `jsonwebtoken`) in Worker or browser code.
- No Express or long-running Node server; no Supabase.
- Data storage mode for this build: **simple** (default is `simple` when unspecified).
- All domain tables and indexes are defined in `migrations/0001_init.sql` and match the Interface contract below.

### 7.2 Interface contract

Default columns below are concrete starting points to refine — do **not** invent extra tables or replace these defaults without updating this contract first.

#### File tree and key signatures

```
src/
  main.tsx, App.tsx, theme.ts
  components/   Layout, TripList, TripDetail, states/
  pages/        Home, About, Terms, Privacy, Contact, TripListPage, TripDetailPage
  lib/
    api.ts      // typed fetch helpers
    schemas.ts  // TripCreateSchema, TripRowSchema; DriverCreateSchema, DriverRowSchema
  i18n/         en.ts
functions/
  api/          trips.ts   // list/create/get handlers
  api/          drivers.ts   // list/create/get handlers
  api/          auth.ts           // register, sign-in, sign-out
  api/          health.ts         // GET /api/health → { status: "ok" }
migrations/    0001_init.sql
wrangler.toml  # D1 binding DB
// Key signatures (implement exactly these names; refine bodies as needed)
export function listTrips(db: D1Database, userId: string): Promise<TripRow[]>
export function getTrip(db: D1Database, id: string): Promise<TripRow | null>
export function createTrip(db: D1Database, input: TripCreate, userId: string): Promise<TripRow>
export function hashPassword(password: string, salt: Uint8Array): Promise<ArrayBuffer>
export function verifyPassword(password: string, salt: Uint8Array, hash: ArrayBuffer): Promise<boolean>
export function createSession(db: D1Database, userId: string): Promise<{ token: string; expiresAt: string }>
export async function onRequestGet(context: EventContext): Promise<Response>  // per route file
```

#### D1 schema (DDL)

```sql
CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  salt TEXT NOT NULL,
  created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  token_hash TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON sessions(user_id);

-- Default columns for Trip; refine field names when product copy is known.
CREATE TABLE IF NOT EXISTS trips (
  id TEXT PRIMARY KEY,
  created_at TEXT NOT NULL,
  user_id TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '''',
  updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_trips_user_id ON trips(user_id);

-- Default columns for Driver; refine field names when product copy is known.
CREATE TABLE IF NOT EXISTS drivers (
  id TEXT PRIMARY KEY,
  created_at TEXT NOT NULL,
  user_id TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '''',
  updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_drivers_user_id ON drivers(user_id);
```

All queries are parameterized. Validate every input with Zod at the boundary.

#### API surface, Zod schemas, and examples

### Trip

| Method | Path | Purpose |
|--------|------|---------|
| GET | `/api/trips` | List trips |
| POST | `/api/trips` | Create one Trip |
| GET | `/api/trips/:id` | Get one by id |

- Zod: `TripCreateSchema`, `TripUpdateSchema`, `TripRowSchema`
- Handler file: `functions/api/trips.ts`

**Example contracts**

GET /api/trips
Request:  (no body; optional query `?q=` for title search)
Response: 200 { "items": [{ "id": "rem_01", "title": "Trip example", "description": "", "createdAt": "2026-08-01T09:00:00.000Z", "updatedAt": "2026-08-01T09:00:00.000Z" }] }
Errors:   500 { "error": "Internal server error" } on unexpected failure

POST /api/trips
Request:  { "title": "Trip example", "description": "Scheduled care task" }
Response: 201 { "id": "rem_01", "title": "Trip example", "description": "Scheduled care task", "createdAt": "2026-08-01T09:00:00.000Z", "updatedAt": "2026-08-01T09:00:00.000Z" }
Errors:   400 { "error": "<message>" } on validation failure

GET /api/trips/:id
Request:  (no body; path param `id`)
Response: 200 { "id": "rem_01", "title": "Trip example", "description": "", "createdAt": "2026-08-01T09:00:00.000Z", "updatedAt": "2026-08-01T09:00:00.000Z" }
Errors:   404 { "error": "Not found" } when id is missing; 400 { "error": "<message>" } on invalid id

### Driver

| Method | Path | Purpose |
|--------|------|---------|
| GET | `/api/drivers` | List drivers |
| POST | `/api/drivers` | Create one Driver |
| GET | `/api/drivers/:id` | Get one by id |

- Zod: `DriverCreateSchema`, `DriverUpdateSchema`, `DriverRowSchema`
- Handler file: `functions/api/drivers.ts`

**Example contracts**

GET /api/drivers
Request:  (no body; optional query `?q=` for title search)
Response: 200 { "items": [{ "id": "rem_01", "title": "Driver example", "description": "", "createdAt": "2026-08-01T09:00:00.000Z", "updatedAt": "2026-08-01T09:00:00.000Z" }] }
Errors:   500 { "error": "Internal server error" } on unexpected failure

POST /api/drivers
Request:  { "title": "Driver example", "description": "Scheduled care task" }
Response: 201 { "id": "rem_01", "title": "Driver example", "description": "Scheduled care task", "createdAt": "2026-08-01T09:00:00.000Z", "updatedAt": "2026-08-01T09:00:00.000Z" }
Errors:   400 { "error": "<message>" } on validation failure

GET /api/drivers/:id
Request:  (no body; path param `id`)
Response: 200 { "id": "rem_01", "title": "Driver example", "description": "", "createdAt": "2026-08-01T09:00:00.000Z", "updatedAt": "2026-08-01T09:00:00.000Z" }
Errors:   404 { "error": "Not found" } when id is missing; 400 { "error": "<message>" } on invalid id
### Auth

| Method | Path | Purpose |
|--------|------|---------|
| POST | `/api/auth/register` | Create account |
| POST | `/api/auth/sign-in` | Start session |
| POST | `/api/auth/sign-out` | End session |

- Zod: `RegisterSchema`, `SignInSchema`
- Handler file: `functions/api/auth.ts`

**Example contracts**

POST /api/auth/register
Request:  { "email": "owner@example.com", "password": "correct-horse-battery" }
Response: 201 { "id": "usr_01", "email": "owner@example.com", "createdAt": "2026-08-01T09:00:00.000Z" }
Errors:   400 { "error": "<message>" } on validation failure; 409 { "error": "Email already registered" }

Also required:

| Method | Path | Purpose |
|--------|------|---------|
| GET | `/api/health` | Liveness — `{ "status": "ok" }` |

**Example — health**

GET /api/health
Request:  (no body)
Response: 200 { "status": "ok" }
Errors:   500 { "error": "Internal server error" } on unexpected failure

#### Client route map

| Path | Page |
|------|------|
| `/` | Home |
| `/trips` | List |
| `/trips/:id` | Detail |
| `/about` | About |
| `/terms` | Terms |
| `/privacy` | Privacy |
| `/contact` | Contact |
| `/sign-in`, `/register` | Auth |

### 7.3 Design specifications

These are **checkable** requirements for the UI system. A visual + axe review must pass at the listed viewports in both themes.

#### Theme and tokens

- [ ] Semantic theme tokens only (no raw hex/rgb/px for color/space in components). Tokens resolve per theme (light + dark).
- [ ] Light and dark themes ship with a visible theme toggle. Pick a **brand default** and state it; a saved choice always wins and persists. Following the system preference is a valid choice, not the only one — a product designed dark-first should open dark, or most visitors never see the design it was built as.
- [ ] WCAG AA contrast: at least **4.5:1** for body text, **3:1** for large text and UI chrome. Measure with **axe-core**, not hand-parsed CSS.

#### Type and spacing

- [ ] Type scale from the design system (body floor **16px** / scale step that maps to 16px minimum for readable body copy).
- [ ] Spacing scale from design tokens (consistent rhythm; no one-off magic numbers for layout gaps).
- [ ] Minimum touch target **44×44px** for interactive controls (R1.1).
- [ ] Safe-area insets respected on sticky bars and primary CTAs (`env(safe-area-inset-*)`).

#### Premium shell (required pages)

- [ ] Sticky top nav with brand mark, primary links, clear **hover** and **active** states (not bare text links).
- [ ] Breadcrumbs on inner/detail pages.
- [ ] Required routes: **Home, About, Terms, Privacy, Contact** with unique title/description/OG per route.
- [ ] Professional multi-column footer; real brand mark (not emoji).
- [ ] Loading, error, and empty states on every data screen; confirm before destructive actions.

#### Desktop width (blocker)

- [ ] Every route''s **painted content** occupies at least **80% of the viewport** at both
      **1440** and **1920**. Measure what is drawn — text via its own client rects, plus
      anything painting a background/border/shadow — **never a container box**. A `<div>`
      or `<h1>` is 100% wide by default, so measuring the container reports ~93% for a page
      whose content sits in the left third. That exact mistake hid four narrow pages here.
- [ ] **No `maxWidth` cap in a JS style object.** Width belongs in a CSS class where a media
      query can lift it; an inline style beats a class, so an inline cap is unliftable by
      definition. (`100%` is fine — it caps nothing. A fixed `width` on an icon, badge or
      1px divider is fine. `minWidth: 0` is the flex/grid shrink idiom and is fine.)
- [ ] Protect the line measure with **column counts, never by starving the container** — and
      let the column count follow the CONTENT (a `:has()` quantity query), or a page with two
      sections leaves an empty third column and reads as 60% of the screen.

#### Responsive verification

- [ ] No overlapping or clipped text at **375px**. An ellipsis is not overflow: a truncated
      label still fails, and only a rendered screenshot shows it.
- [ ] Verified at **375 / 768 / 1280** in **both** light and dark themes via real screenshots + axe (zero serious/critical).

### 7.3a Design direction (binding)

The constraints in §7.3 are identical for every app RedAnvil generates. They are not a
design. This section is, and it is **binding**: an implementation that satisfies every
constraint while looking like a generic centred column under a sticky header has not built
this spec.

#### Layout archetype — Map + list

A spatial surface paired with a synchronised list; selecting in one drives the other.

```
┌────────────────────────────────────────────────┐
│                              ┌───────────────┐ │
│        spatial surface       │ synced list   │ │
│        (map / floorplan /    │ hover ↔ pin   │ │
│         seating / chart)     │               │ │
│                              └───────────────┘ │
└────────────────────────────────────────────────┘
```

**At 375px:** Surface takes the top 45vh; the list is a draggable sheet over it.

**Why this shell:** anything with location or physical arrangement.

**Do not fall back to:** Split workbench, Command canvas, Timeline chronicle. Those are different products. If this
archetype genuinely does not fit the domain, say so in the PR and argue for another one —
do not quietly build a centred list instead.

#### Visual direction — Expressive dark

- **Type:** A geometric sans for headings, neutral sans for body.
- **Shape:** Pill controls, gradient-edged surfaces, glow instead of drop shadow.
- **Density:** Cinematic: large hero type, deliberate empty space, few competing elements.
- **Colour:** Dark-first with a luminous accent; the light theme is a real design, not an inversion.

This direction sets what the tokens are, not whether to use them. Every constraint in §7.3
still holds: semantic tokens only, AA contrast measured with axe-core, a 16px body floor,
44px touch targets, a real light theme and a real dark theme.

#### Before you write components

> The archetype and direction above are a **starting hypothesis, not a decision** (R24).
> They were derived from the prompt, and nobody has chosen them yet. Do not implement
> them straight through — the two steps below come first, and they are blockers.

- [ ] **Run the prior-art pass (R23, R29, R31) — three artifacts, before any code.**
      The `prior-art` skill runs all three: what the category looks like, what already
      exists to build it with (and whether its licence and RUNTIME fit), and what the
      real competitors ship. They write `SOURCES.md`, `INTEGRATIONS.md` and
      `COMPETITORS.md`. **A missing file means the step did not run.** Missing table
      stakes is a defect even when this spec never named it — the spec is not the
      standard, the category is.
- [ ] **Write real Terms, Privacy, About and Contact (R30)** with the `legal-pages`
      skill. Terms and Privacy need at least 150 words across at least 3 headed
      sections, and every statement must be TRUE for this app — boilerplate about
      cookies you do not set is as wrong as omitting a disclosure. The scaffold ships
      an explicit unwritten-document marker instead of copy, precisely so that
      leaving it in place fails the gate rather than passing as a finished page.
- [ ] **Generate the brand mark with the `brand-logo` skill.** Ban only what is
      disqualifying, never your taste: a brief that forbade gradients and the
      category''s own convention produced flat line art from a tool that had better.
- [ ] **Run the App Store intake (R23).** Search the real store by this app''s own domain
      keywords and look at what shipped in the category:
      `node ~/.claude/skills/design-inspo-x/scripts/appstore_refs.mjs --terms "<domain
      keywords>" --out design-refs/<slug>`. It ranks by rating count and writes
      `SOURCES.md`. **No `SOURCES.md` means this step did not run.** Then name, per app,
      the ONE component you are borrowing, and change its shape, density or position.
      Never take a brand mark, palette, or a whole screen layout.
- [ ] **Present options and let the user pick (R24).** Minimum three, structurally
      distinct — if editing a palette turns one into another, it is one option. Every
      option renders dark AND light at 375 in a gallery, and the folder and the gallery
      both get opened. Expect the answer to be a MIX of options, so design them to blend.
      Accent colour, default theme, which view lands first, and the logo are the user''s
      calls — never decide them silently.
- [ ] Generate the logo and any backgrounds/icons in THIS phase, review every one by eye,
      and say plainly which are unusable. Never iterate a brand mark against a deployed site.
- [ ] **Measure the approved mockup before the app inherits it (R25).** A mockup is drawn
      by eye and an eye cannot measure contrast. Run axe-core against it, and check its
      type scale against the 16px body floor, BEFORE building on its tokens. An approved
      palette here shipped a tertiary tone that failed AA in both themes and a 14px body
      line; fixing a token after the build means re-measuring and re-gating every screen
      that inherited it. Check the approved logo at its REAL rendered size, on both
      themes, beside the accent — adjust the rendering or recolour the asset, never
      silently swap the mark the user chose.
- [ ] Build the token set for the chosen direction FIRST, then the shell, then screens.
      Choosing colours while writing components is how everything drifts back to default.
- [ ] Sketch the archetype at 375 and 1280 before implementing. If the mobile resolution is
      "the same thing but narrower", the archetype has not actually been applied.

#### Do not copy RedAnvil

RedAnvil''s own app-builder and dashboard are reference *implementations of the rules*, not a
template to reproduce. Reusing their shell, palette, or component structure is the specific
failure this section exists to prevent.

## 8. Core Features (MVP first)

MVP features are the **minimum** set that solves the stated problem. An agent must be able to ship only the MVP set and have a working product. Build MVP first; Beyond MVP only after MVP acceptance is green.

### MVP

### F1 — Browse & search Trip **[MVP]**

Users can open the trips list, search by title, and see matching rows or an empty state.

### F2 — Trip detail **[MVP]**

Clicking a list row opens the full Trip record with title, description, and a back link.

### F3 — Accounts **[MVP]**

Register and sign in with Web Crypto (PBKDF2 + HMAC-SHA256 sessions); data is scoped to the signed-in user.

### F4 — Manage Trip **[MVP]**

Create, edit, and delete trips with confirmation before delete.

### Beyond MVP

### F5 — Trip history

Every recorded trip is kept and shown over time, so a change can be seen rather than inferred.

### F6 — Manage Driver

Create, edit, and delete drivers with confirmation before delete.

### F7 — Required pages & SEO

Ship Home, About, Terms, Privacy, Contact with per-route SEO, sitemap, and robots.txt.

## 9. Acceptance Criteria

Each feature has an ID for task and UAT binding. Every bullet is one testable condition; bind each to a named test in §10.

### F1 — Browse & search Trip

**Acceptance criteria**
- GIVEN seeded trips exist WHEN the user opens the list THEN each row shows title and a link to detail
- GIVEN seeded trips exist WHEN the user enters a query that matches one title THEN only matching rows render
- GIVEN no trips exist WHEN the list loads THEN an empty state explains how to add one
- GIVEN the API returns 500 WHEN the list loads THEN an error message with a retry action is shown

### F2 — Trip detail

**Acceptance criteria**
- GIVEN a Trip id that exists in D1 WHEN the user opens /trips/:id THEN the page shows title, description, and a back link to the list
- GIVEN an unknown id WHEN the user opens /trips/:id THEN a not-found state with a path back to the list is shown
- GIVEN the API returns 500 WHEN detail loads THEN an error message with a retry action is shown

### F3 — Accounts

**Acceptance criteria**
- GIVEN no session cookie WHEN the user registers with valid email and password THEN they receive a session and land on a signed-in view
- GIVEN a registered account WHEN the user signs out and signs back in with the same credentials THEN they receive a session again
- GIVEN two users with their own rows WHEN user A lists domain data THEN only user A rows are returned
- GIVEN invalid credentials WHEN the user signs in THEN a 401 error message is shown and no session is set

### F4 — Manage Trip

**Acceptance criteria**
- GIVEN the manage form is open WHEN the user creates a Trip with a valid title THEN the list includes the new row
- GIVEN an existing Trip WHEN the user edits its title and saves THEN the list and detail show the new title
- GIVEN an existing Trip WHEN the user confirms delete THEN the row is gone from the list
- GIVEN an existing Trip WHEN the user cancels delete THEN the row remains
- GIVEN invalid input (empty title) WHEN the user submits create THEN a 400 validation message is shown and no row is created

### F5 — Trip history

**Acceptance criteria**
- GIVEN recorded entries WHEN the user opens the history THEN entries appear newest first with their timestamps
- GIVEN no entries WHEN the history loads THEN an empty state explains what will appear here

### F6 — Manage Driver

**Acceptance criteria**
- GIVEN the Driver manage form is open WHEN the user creates a Driver with a valid title THEN the list includes the new row
- GIVEN an existing Driver WHEN the user confirms delete THEN the row is gone from the list
- GIVEN invalid input WHEN the user submits create THEN a validation error is shown and no row is created

### F7 — Required pages & SEO

**Acceptance criteria**
- GIVEN the production build is served WHEN each required route is requested THEN each returns 200 with a unique title and description
- GIVEN the production build WHEN sitemap.xml and robots.txt are requested THEN both files exist and are non-empty
- GIVEN each required page WHEN the document head is inspected THEN OG title/description are present and unique per route

## 10. Test Plan

Named cases per feature (not categories). Acceptance bullets in §9 map to these names.

### F1 — Browse & search Trip

**Unit**
- `filterTrips_byQuery_matchesTitle`
- `filterTrips_byQuery_emptyReturnsEmpty`

**Integration**
- `GET /api/trips returns 200 with items array`
- `GET /api/trips?q= matches title`

**E2E**
- `trips-list shows rows`
- `trips-list empty state`
- `trips-list error + retry`

### F2 — Trip detail

**Unit**
- `TripRowSchema_acceptsValidRow`
- `TripRowSchema_rejectsMissingId`

**Integration**
- `GET /api/trips/:id returns 200 for existing`
- `GET /api/trips/:id returns 404 for missing`

**E2E**
- `trips-detail shows fields`
- `trips-detail not-found state`

### F3 — Accounts

**Unit**
- `hashPassword_isDeterministicWithSalt`
- `verifyPassword_rejectsWrongPassword`

**Integration**
- `POST /api/auth/register returns 201 + Set-Cookie`
- `POST /api/auth/sign-in returns 200 with valid creds`
- `list endpoints scope by user_id`

**E2E**
- `auth register → sign-out → sign-in flow`
- `auth blocks cross-user data`

### F4 — Manage Trip

**Unit**
- `TripCreateSchema_requiresTitle`
- `TripCreateSchema_acceptsValid`

**Integration**
- `POST /api/trips returns 201`
- `POST /api/trips returns 400 on empty title`
- `DELETE or update path removes/updates row`

**E2E**
- `trips-crud create`
- `trips-crud edit`
- `trips-crud delete confirm/cancel`

### F5 — Trip history

**Unit**
- `sortHistory_newestFirst`

**Integration**
- `GET /api/history returns 200 with ordered entries`

**E2E**
- `history shows recorded entries`

### F6 — Manage Driver

**Unit**
- `DriverCreateSchema_requiresTitle`

**Integration**
- `POST /api/drivers returns 201`
- `POST /api/drivers returns 400 on invalid`

**E2E**
- `drivers-crud create and delete`

### F7 — Required pages & SEO

**Unit**
- `seoMeta_uniquePerRoute`

**Integration**
- `GET /about /terms /privacy /contact return 200`
- `GET /sitemap.xml and /robots.txt exist`

**E2E**
- `required-pages smoke all five routes`

## 11. Build Plan (vertical slices)

Each slice is a **tracer bullet** that crosses DB + API + UI + tests for **one** capability. Ship and verify a slice before starting the next. Dependency order is explicit. Do **not** build horizontally (all DDL, then all APIs, then all UI) — that delays end-to-end feedback.

### Slice 0 — Walking skeleton [MVP]
- DB: migrations/0001_init.sql with DDL for Trip, Driver + users/sessions; wrangler.toml D1 binding DB
- API: GET /api/health → `{ "status": "ok" }` (functions/api/health.ts)
- UI: Home page shell (Layout + theme tokens + i18n stub) loads at `/`
- Tests: unit: health handler returns ok; e2e: home loads 200
- Verify: `npx tsc --noEmit && npx vitest run && npm run build; curl -sf http://127.0.0.1:<port>/api/health → {"status":"ok"}`  → expected result: command exits 0 / assertions pass
- Depends on: None (first slice)

### Slice 1 — Browse & search Trip [MVP]
- DB: Use `trips` table from Slice 0; seed rows for list tests
- API: GET /api/trips (+ optional ?q=); contract in §7
- UI: TripListPage at `/trips` with loading / empty / error states
- Tests: `filterTrips_byQuery_matchesTitle`, `filterTrips_byQuery_emptyReturnsEmpty`, `GET /api/trips returns 200 with items array`, `GET /api/trips?q= matches title`, `trips-list shows rows`, `trips-list empty state`, `trips-list error + retry`
- Verify: `npx vitest run functions/api/trips.test.ts && npx playwright test tests/trips-list.spec.ts`  → expected result: command exits 0 / assertions pass
- Depends on: Slice 0

### Slice 2 — Trip detail [MVP]
- DB: Read one row from `trips`
- API: GET /api/trips/:id
- UI: TripDetailPage at `/trips/:id` with back link
- Tests: `TripRowSchema_acceptsValidRow`, `TripRowSchema_rejectsMissingId`, `GET /api/trips/:id returns 200 for existing`, `GET /api/trips/:id returns 404 for missing`, `trips-detail shows fields`, `trips-detail not-found state`
- Verify: `npx playwright test tests/trips-detail.spec.ts`  → expected result: command exits 0 / assertions pass
- Depends on: Slice 1

### Slice 3 — Accounts [MVP]
- DB: users + sessions tables (from Slice 0 DDL)
- API: POST /api/auth/register, /api/auth/sign-in, /api/auth/sign-out
- UI: Register + Sign-in pages; session-aware nav
- Tests: `hashPassword_isDeterministicWithSalt`, `verifyPassword_rejectsWrongPassword`, `POST /api/auth/register returns 201 + Set-Cookie`, `POST /api/auth/sign-in returns 200 with valid creds`, `list endpoints scope by user_id`, `auth register → sign-out → sign-in flow`, `auth blocks cross-user data`
- Verify: `npx vitest run functions/api/auth.test.ts && npx playwright test tests/auth.spec.ts`  → expected result: command exits 0 / assertions pass
- Depends on: Slice 2

### Slice 4 — Manage Trip [MVP]
- DB: INSERT/UPDATE/DELETE on `trips`
- API: POST /api/trips (+ update/delete as specified); Zod TripCreateSchema
- UI: Create/edit form + confirm dialog before delete on Trip manage UI
- Tests: `TripCreateSchema_requiresTitle`, `TripCreateSchema_acceptsValid`, `POST /api/trips returns 201`, `POST /api/trips returns 400 on empty title`, `DELETE or update path removes/updates row`, `trips-crud create`, `trips-crud edit`, `trips-crud delete confirm/cancel`
- Verify: `npx vitest run src/lib/schemas.test.ts && npx playwright test tests/trips-crud.spec.ts`  → expected result: command exits 0 / assertions pass
- Depends on: Slice 3

### Slice 5 — Trip history
- DB: Query `trips`; add indexes for the fields this feature filters or sorts on
- API: POST /api/search — accepts the query and every filter named in §9, returns ordered results
- UI: The screens this feature needs, per §7.3a: query input, results, and its controls
- Tests: `sortHistory_newestFirst`, `GET /api/history returns 200 with ordered entries`, `history shows recorded entries`
- Verify: `npx vitest run && npx playwright test tests/search.spec.ts`  → expected result: command exits 0 / assertions pass
- Depends on: Slice 4

### Slice 6 — Manage Driver
- DB: Use `drivers` table from Slice 0
- API: GET/POST /api/drivers, GET /api/drivers/:id
- UI: Driver list/detail/manage screens
- Tests: `DriverCreateSchema_requiresTitle`, `POST /api/drivers returns 201`, `POST /api/drivers returns 400 on invalid`, `drivers-crud create and delete`
- Verify: `npx vitest run && npx playwright test tests/drivers-crud.spec.ts`  → expected result: command exits 0 / assertions pass
- Depends on: Slice 5

### Slice 7 — Required pages & SEO
- DB: No domain change
- API: Static routes only
- UI: Home, About, Terms, Privacy, Contact pages + sitemap.xml + robots.txt + per-route SEO
- Tests: `seoMeta_uniquePerRoute`, `GET /about /terms /privacy /contact return 200`, `GET /sitemap.xml and /robots.txt exist`, `required-pages smoke all five routes`
- Verify: `test -f public/sitemap.xml && test -f public/robots.txt && npx playwright test tests/required-pages.spec.ts`  → expected result: command exits 0 / assertions pass
- Depends on: Slice 6

### Slice 8 — A11y, visual, and full gate
- DB: No schema change
- API: No new endpoint
- UI: axe-clean interactive controls; light + dark at 375 / 768 / 1280
- Tests: `a11y zero serious/critical`, visual regression screenshots
- Verify: `npx playwright test tests/a11y.spec.ts; from monorepo root: npm run gate -- build-an-app-for-tracking-tesla-driving-stats --threshold 90`  → expected result: command exits 0 / assertions pass
- Depends on: Slice 7

## 12. Verification & Gates

**Target score:** >= **90** (see frontmatter `threshold`). Stop only when the RedAnvil gate reports score >= threshold with zero tier-1 blockers. Do not trust self-report.

Run from the **app directory** unless noted:

1. `npx tsc --noEmit`
2. `npx eslint . --max-warnings 0`
3. `npx vitest run`
4. `npm run build`
5. Runtime health (after `npx wrangler pages dev ./dist` or equivalent local serve):
   `curl -sf http://127.0.0.1:<port>/api/health` → JSON including `"status":"ok"`
6. Playwright primary flow + axe (zero serious/critical violations)
7. Visual review screenshots at 375 / 768 / 1280 (light + dark)

From the **RedAnvil monorepo root** (see root `README.md` / `npm run gate`):

```bash
npm run gate -- build-an-app-for-tracking-tesla-driving-stats --threshold 90
```

Optional excludes when a check is not applicable: `--na ci,process` (only with documented reason).

## 13. Coding Standard (must)

Echo of `rules/base-15.md` + `rules/per-app-pack.md`. Treat every line as a **must**.

- [ ] **Strict TypeScript** — `strict` on; zero `any`; no untyped defs.
- [ ] **Fail closed** — typed errors; unknown/partial state is an explicit error on screen and in APIs; never silent success.
- [ ] **Parameterized D1 only** — no string-concatenated SQL.
- [ ] **Zod at the boundary** — validate every request body/query; reject invalid input with 400.
- [ ] **No Node-only globals/modules** in Worker or browser code (`process`, `Buffer`, `better-sqlite3`, `bcrypt`, `jsonwebtoken`).
- [ ] **No secrets in code** — env / Cloudflare secrets only; never log secrets or PII.
- [ ] **Real data only** — no filler copy, dummy rows, placeholder metrics, or fabricated scores.
- [ ] **Smallest correct diff** — no speculative abstraction, no padding, no drive-by refactors.
- [ ] **Single-purpose files** — small modules; pages compose named components.
- [ ] **All user-facing copy** lives in the locale bundle (`src/i18n/en.ts`); no hardcoded UI strings.
- [ ] **Theme tokens only** — colors/spacing/type from the design system; WCAG AA.
- [ ] **Platform** — Cloudflare Pages + Pages Functions + D1; Web Crypto for auth when auth is in scope; no Express/Supabase.

### Platform constraints checklist

- **Platform:** Vite + React + TypeScript (strict) + Tailwind + React Router; Cloudflare Pages Functions + D1. No Express, no long-running Node server, no Supabase.
- **Input safety:** parameterized SQL only; Zod validate every request body/query at the boundary.
- **UX states:** every data screen defines loading, error, and empty; confirm before destructive actions.
- **Fail closed:** typed errors; never log secrets or PII. Real data only — no fabricated metrics.

## 14. PRD Self-Check

Completeness graded from this document at generation time (not a hardcoded score).

- [x] Machine frontmatter present
- [x] Problem statement present
- [x] At least one user story
- [x] At least one MVP feature marked
- [x] Every feature has ≥1 acceptance bullet
- [x] DDL present for every entity (or explicit none)
- [x] Every vertical slice has a verify command
- [x] No placeholder tokens (TBD/TODO/lorem) in body
- [x] Gate command named with threshold
- [x] API example includes request and response bodies
- [x] All 14 standard sections present in order
- [x] Success Outcome (definition of done) present

**Grade: 12/12 checks passed (100%)**

## Initial build prompt (paste into the coder)

> Implement this spec as **vertical slices** (§11, Slice 0→Slice 8). Honor **§7** Technical Requirements (architecture, DDL, routes, Zod names, signatures, design specs) before polish. Satisfy every MVP feature (F1, F2, F3, F4) and its acceptance bullets (**§9**) with the named tests in **§10** (F1, F2, F3, F4, F5, F6, F7). Follow **§13** coding standard. Do not implement **§5** non-goals. After each slice, run that slice''s Verify command. Do not stop until **§12** clears: `npx tsc --noEmit`, `npx eslint . --max-warnings 0`, `npx vitest run`, `npm run build`, runtime `curl …/api/health`, and from monorepo root `npm run gate -- build-an-app-for-tracking-tesla-driving-stats --threshold 90` at score >= 90. No push, no deploy, no secrets. Smallest correct diff. Strict TypeScript, zero `any`.

_Effort (human/orchestrator only): ~4 iterations, ~1,476,000 tokens (medium confidence)._
',
  '2026-07-30T00:00:00.000Z'
);
