/**
 * The definition of done, embedded for the PRD generator.
 *
 * WHY EMBEDDED RATHER THAN READ
 * -----------------------------
 * `docs/DONE-CHECKLIST.md` is the single source of truth and the orchestrator
 * parses it directly. This generator runs in the browser, so it cannot read that
 * file at generate time. The rows are therefore embedded here, and
 * `doneChecklist.test.ts` re-parses the real document and fails when this copy
 * has drifted. That test is the only thing that makes an embedded duplicate
 * safe -- do not delete it.
 *
 * Generated by `npx tsx scripts/regen-done-checklist.mts`. Edit the document,
 * not this file.
 */

export interface ChecklistRow {
  readonly id: string;
  readonly mustBeTrue: string;
  readonly evidence: string;
}

export interface ChecklistSection {
  readonly letter: string;
  readonly title: string;
  readonly rows: readonly ChecklistRow[];
}

export const DONE_CHECKLIST_SECTIONS: readonly ChecklistSection[] = [
  {
    letter: "A",
    title: "The build itself",
    rows: [
      { id: "A1", mustBeTrue: "`tsc --noEmit` exits 0", evidence: "terminal output, read" },
      { id: "A2", mustBeTrue: "`eslint . --max-warnings 0` exits 0", evidence: "terminal output, read" },
      { id: "A3", mustBeTrue: "Unit tests pass", evidence: "test summary line, read" },
      { id: "A4", mustBeTrue: "Acceptance tests pass", evidence: "Playwright summary, read" },
      { id: "A5", mustBeTrue: "`npm run build` exits 0", evidence: "terminal output, read" },
      { id: "A6", mustBeTrue: "Coverage ≥ recorded high-water", evidence: "`coverage/coverage-summary.json`, read" }
    ]
  },
  {
    letter: "B",
    title: "The backend is real",
    rows: [
      { id: "B1", mustBeTrue: "Every route returns 2xx with a non-empty body", evidence: "captured HTTP response body, read" },
      { id: "B2", mustBeTrue: "Responses come from the database, not literals", evidence: "`.prepare()` call sites + a live query count" },
      { id: "B3", mustBeTrue: "Not-found paths return 404", evidence: "captured response" },
      { id: "B4", mustBeTrue: "Query parameters actually filter", evidence: "two responses with **different** row counts" },
      { id: "B5", mustBeTrue: "A route that looks like it works actually exists", evidence: "the served body" }
    ]
  },
  {
    letter: "C",
    title: "The page, seen",
    rows: [
      { id: "C1", mustBeTrue: "Screenshots captured at 375 / 768 / 1280", evidence: "PNG files at the current commit" },
      { id: "C2", mustBeTrue: "Those screenshots **opened and viewed**", evidence: "the displayed image" },
      { id: "C3", mustBeTrue: "Light theme inverts **every** region", evidence: "light + dark screenshots, compared by eye" },
      { id: "C4", mustBeTrue: "The theme control is discoverable", evidence: "the screenshot" },
      { id: "C5", mustBeTrue: "Painted content ≥ 80% of viewport at 1440/1920", evidence: "`desktop_width` report" },
      { id: "C6", mustBeTrue: "No overlap or clipping at 375px", evidence: "the screenshot" },
      { id: "C7", mustBeTrue: "Zero console errors", evidence: "console log from the real load" },
      { id: "C8", mustBeTrue: "Inner and detail pages show breadcrumbs", evidence: "live `nav` named breadcrumb + parent link" },
      { id: "C9", mustBeTrue: "The chosen design was picked from three distinct options", evidence: "`design-refs/design-options/` (≥3) + `DECISION.md`" },
      { id: "C10", mustBeTrue: "A control's result renders where the person is looking", evidence: "measured y of nearest changed element inside the first viewport at 375 and 1280" }
    ]
  },
  {
    letter: "D",
    title: "Content is real",
    rows: [
      { id: "D1", mustBeTrue: "Terms ≥ 1200 words, ≥ 8 sections", evidence: "`design_audit` word/section counts" },
      { id: "D2", mustBeTrue: "Privacy ≥ 1200 words, ≥ 8 sections", evidence: "same" },
      { id: "D3", mustBeTrue: "Required routes render **distinct** pages", evidence: "per-route titles and word counts" },
      { id: "D4", mustBeTrue: "Every legal claim is **true of this app**", evidence: "the code path proving it" },
      { id: "D5", mustBeTrue: "Data rows trace to a cited source", evidence: "per-row citation + a verification run" },
      { id: "D6", mustBeTrue: "Brand mark is a real generated asset", evidence: "the image, opened" },
      { id: "D7", mustBeTrue: "The mark reads at 32px", evidence: "the **downscaled** image, opened" },
      { id: "D8", mustBeTrue: "Terms and Privacy meet the reference standard", evidence: "word/h2 floors + required topic coverage" },
      { id: "D9", mustBeTrue: "Structured data and canonical URL", evidence: "valid JSON-LD + absolute `rel=canonical` on home" },
      { id: "D10", mustBeTrue: "The brand mark renders at a real size", evidence: "measured header mark height at 1280 and 375" },
      { id: "D11", mustBeTrue: "Domain items link to real, resolving external resources", evidence: "live crawl of item detail routes + HEAD/GET of every external link (2xx/3xx, browser UA)" }
    ]
  },
  {
    letter: "E",
    title: "Shipped",
    rows: [
      { id: "E1", mustBeTrue: "Git repo with a GitHub `origin`", evidence: "`git remote -v`" },
      { id: "E2", mustBeTrue: "HEAD pushed", evidence: "`git rev-list origin/<branch>..HEAD` empty" },
      { id: "E3", mustBeTrue: "Production URL returns 200", evidence: "captured response" },
      { id: "E4", mustBeTrue: "Served asset hash == local `dist`", evidence: "both hashes, compared" },
      { id: "E5", mustBeTrue: "The server measured is **this app**", evidence: "the served `<title>`" },
      { id: "E6", mustBeTrue: "Every binding declared in config exists in the deployed environment", evidence: "live 503 / \"binding unavailable\" probe" }
    ]
  },
  {
    letter: "F",
    title: "Scored",
    rows: [
      { id: "F1", mustBeTrue: "Gate score ≥ threshold", evidence: "`results/<slug>.json`, read" },
      { id: "F2", mustBeTrue: "Zero rules with `passed: false`", evidence: "the same file" },
      { id: "F3", mustBeTrue: "Every verdict's evidence post-dates its commit", evidence: "freshness output" },
      { id: "F4", mustBeTrue: "Result reproduces independently", evidence: "`verify_results` output" },
      { id: "F5", mustBeTrue: "An independent judge reviewed the **diff**", evidence: "judge verdicts with `file:line`" }
    ]
  },
  {
    letter: "G",
    title: "The measurement itself",
    rows: [
      { id: "G1", mustBeTrue: "A new check was run against a **known-bad** input and failed", evidence: "a check that cannot fail carries no information" },
      { id: "G2", mustBeTrue: "Two runs of the same measurement agree", evidence: "if they disagree, report neither until you know which is wrong" },
      { id: "G3", mustBeTrue: "A flattering first result was re-checked", evidence: "every new measurement in one session was wrong on first run, always in the flattering direction" },
      { id: "G4", mustBeTrue: "The tool is the standard one", evidence: "axe-core for contrast, never a hand-rolled parser" },
      { id: "G5", mustBeTrue: "The engine is named before comparing", evidence: "`devices['iPhone 13']` is **WebKit**, not Chromium" },
      { id: "G6", mustBeTrue: "A new meta-rule was run against a fixture that **provably fails it**, and the non-zero exit code was read", evidence: "a fixture path that merely *resolves* is not a fixture that *ran* -- `meas-known-bad` once returned pass on an unresolvable path, so prose describing a failing case satisfied the check with nothing executed" },
      { id: "G7", mustBeTrue: "A \"two run\" record holds two genuinely independent measurements", evidence: "`meas-two-run` counted one computed value written twice as two runs agreeing; a check that cannot fail carries no information. Fixing this can create a new false failure: capturing both timestamps at write time makes a fast measurement byte-identical, which then fails the very check meant to catch a duplicate -- timestamps must be captured as each run completes, not backfilled afterward" }
    ]
  }
];

/** Heading the self-check looks for to prove the block was emitted. */
export const DEFINITION_OF_DONE_HEADING = '### Definition of Done (non-optional)';

/**
 * Render the definition of done for inclusion in a generated PRD.
 *
 * Emitted into every PRD so a builder is handed all of the finish-line
 * conditions up front instead of discovering them one gate failure at a time.
 * `selfCheck` fails any PRD that does not contain it.
 *
 * @returns Markdown for the Definition of Done block.
 */
export function buildDefinitionOfDone(): string {
  const lines: string[] = [
    DEFINITION_OF_DONE_HEADING,
    '',
    'Nothing may be called done, finished, shipped, complete, or working until every',
    'row below has been **measured** and its **evidence artifact opened**. A spec, a',
    'prompt, a plan, or a rule file is never evidence, and neither is an agent',
    'summarising its own work. The gate evaluates every row and fail-closes on any row',
    'that is unmeasured or has no implementation behind it.',
    ''
  ];
  for (const section of DONE_CHECKLIST_SECTIONS) {
    lines.push(`**${section.letter}. ${section.title}**`, '');
    for (const row of section.rows) {
      const evidence = row.evidence === '' ? '' : ` — evidence: ${row.evidence}`;
      lines.push(`- [ ] **${row.id}** — ${row.mustBeTrue}${evidence}`);
    }
    lines.push('');
  }
  return lines.join('\n').trimEnd() + '\n';
}
