import type { Job } from '../schemas/job';
import { legalDocs } from './legalCopy';
import { featureAuditScript, featureManifestJson, coldVisitorScript } from './featureAudit';
import { apiExamplesJson, coverageStateJson } from './apiExamples';

const PAGES = ['Home', 'About', 'Terms', 'Privacy', 'Contact'] as const;

/** Map scaffold field types to SQLite column types. */
const SQL_TYPE: Record<'text' | 'integer' | 'real' | 'blob', string> = {
  text: 'TEXT',
  integer: 'INTEGER',
  real: 'REAL',
  blob: 'BLOB'
};

/** Design tokens shipped inside the generated app (single source for theme). */
const TOKENS_JSON = {
  version: '1.0.0',
  color: {
    bg: '#0b0b0f',
    surface: '#15151d',
    text: '#f5f5f7',
    accent: '#e5484d',
    muted: '#8b8b93',
    border: '#26263049'
  },
  space: { xs: 4, sm: 8, md: 16, lg: 24, xl: 40 },
  radius: { sm: 6, md: 12, lg: 20 },
  type: { scale: [12, 14, 16, 20, 28, 40], family: 'Inter, system-ui, sans-serif' }
} as const;

/**
 * Convert a PascalCase / camelCase entity name to a snake_case SQL table name.
 *
 * @param name - Entity name matching Job.entities[].name.
 * @returns Lowercase snake_case table identifier.
 */
function entityToTableName(name: string): string {
  const snake = name
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .replace(/[^A-Za-z0-9_]+/g, '_')
    .toLowerCase();
  // SQLite unquoted identifiers cannot start with a digit.
  return /^[0-9]/.test(snake) ? `t_${snake}` : snake.length > 0 ? snake : 'items';
}

/**
 * Derive a SQL-safe table name from a kebab-case app slug when no entities exist.
 *
 * @param slug - Job slug (e.g. `demo-app`).
 * @returns Snake_case table name (e.g. `demo_app`).
 */
function slugToTableName(slug: string): string {
  const snake = slug.replace(/-/g, '_').replace(/[^a-z0-9_]/g, '');
  if (snake.length === 0) return 'app_items';
  return /^[0-9]/.test(snake) ? `app_${snake}` : snake;
}

/**
 * Build `migrations/0001_init.sql` from job entities, or a slug-derived table when empty.
 *
 * @param job - Validated scaffold job.
 * @returns SQL text with at least one CREATE TABLE statement.
 */
function migrationSql(job: Job): string {
  const entities =
    job.entities.length > 0
      ? job.entities
      : [
          {
            name: slugToTableName(job.slug),
            fields: [] as { name: string; type: 'text' | 'integer' | 'real' | 'blob' }[]
          }
        ];

  const blocks = entities.map((entity) => {
    const table = entityToTableName(entity.name);
    const fieldLines = entity.fields.map((field) => `  ${field.name} ${SQL_TYPE[field.type]},`);
    const cols = [
      '  id INTEGER PRIMARY KEY AUTOINCREMENT,',
      ...fieldLines,
      '  created_at TEXT NOT NULL'
    ].join('\n');
    return `CREATE TABLE IF NOT EXISTS ${table} (\n${cols}\n);`;
  });

  return (
    `-- Initial D1 schema for ${job.slug}.\n` +
    `-- Generated by RedAnvil scaffold; apply with wrangler d1 migrations apply.\n\n` +
    blocks.join('\n\n') +
    '\n'
  );
}

/**
 * Self-contained SVG Open Graph card for the generated app.
 *
 * @param slug - App slug rendered on the card.
 * @returns SVG markup.
 */
function ogSvg(slug: string): string {
  const safe = slug
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
  return (
    `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630" role="img" aria-label="${safe}">\n` +
    `  <rect width="1200" height="630" fill="#0b0b0f"/>\n` +
    `  <rect x="48" y="48" width="1104" height="534" rx="24" fill="#15151d" stroke="#262630" stroke-width="2"/>\n` +
    `  <text x="96" y="280" fill="#f5f5f7" font-family="Inter, system-ui, sans-serif" font-size="64" font-weight="700">${safe}</text>\n` +
    `  <text x="96" y="360" fill="#8b8b93" font-family="Inter, system-ui, sans-serif" font-size="32">Built with RedAnvil</text>\n` +
    `</svg>\n`
  );
}

/**
 * XML sitemap listing the five required app routes.
 *
 * @param slug - App slug used as the pages.dev host prefix.
 * @returns Sitemap XML.
 */
function sitemapXml(slug: string): string {
  const origin = `https://${slug}.pages.dev`;
  const paths = ['/', '/about', '/terms', '/privacy', '/contact'] as const;
  const urls = paths
    .map((path) => {
      const loc = path === '/' ? `${origin}/` : `${origin}${path}`;
      const priority =
        path === '/' ? '1.0' : path === '/about' || path === '/contact' ? '0.6' : '0.3';
      const changefreq =
        path === '/' ? 'weekly' : path === '/about' || path === '/contact' ? 'monthly' : 'yearly';
      return (
        `  <url>\n` +
        `    <loc>${loc}</loc>\n` +
        `    <changefreq>${changefreq}</changefreq>\n` +
        `    <priority>${priority}</priority>\n` +
        `  </url>`
      );
    })
    .join('\n');
  return (
    `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
    `${urls}\n` +
    `</urlset>\n`
  );
}

/**
 * English locale bundle used by page templates.
 *
 * @param job - Job providing the app name for copy.
 * @returns TypeScript module source.
 */
function i18nEnTs(job: Job, builtAt: string): string {
  // R32: emit a REAL document, never a plausible stub. The previous template
  // produced `'<Name> page for <slug>.'`, and four one-sentence legal pages
  // shipped and passed every check — a stub WAS its finished output. A marker
  // would satisfy R32's letter and still leave a broken page on screen.
  //
  // `legalDocs` returns complete Terms, Privacy, About and Contact that are true
  // of any app this scaffold builds, because the scaffold fixes the stack and
  // can therefore describe it honestly. They ship correct and invite editing.
  const docs = legalDocs(job, builtAt);
  // Home is not a legal document but shares the shape, so every page component
  // can render one structure instead of branching.
  const home = {
    title: job.slug,
    intro: job.prompt,
    sections: [
      {
        heading: 'What this app does',
        body: job.prompt
      }
    ],
    updated: builtAt.slice(0, 10)
  };
  const all = { home, ...docs };
  const pages = (Object.keys(all) as (keyof typeof all)[])
    .map((key) => `  ${key}: ${JSON.stringify(all[key], null, 2).split('\n').join('\n  ')}`)
    .join(',\n');
  return (
    `/**\n` +
    ` * Central English locale bundle for all user-facing copy.\n` +
    ` * Components must reference these keys; no inline UI strings.\n` +
    ` */\n` +
    `export const en = {\n` +
    `  app: {\n` +
    `    name: '${job.slug}',\n` +
    `    primaryNav: 'Primary',\n` +
    `    footerCopyright: '© ${job.slug}'\n` +
    `  },\n` +
    `  pages: {\n${pages}\n  }\n` +
    `} as const;\n`
  );
}

/**
 * Page component that reads title and body from the locale bundle.
 *
 * @param name - Page name (Home, About, …).
 * @returns TypeScript React module source.
 */
function pageComponent(name: string): string {
  const key = name.toLowerCase();
  return (
    `import { DocPage } from '../components/DocPage';
` +
    `import { en } from '../i18n/en';

` +
    `/** ${name} page. Copy lives in the locale bundle (fe-i18n-central-copy). */
` +
    `export function ${name}(): JSX.Element {
` +
    `  return <DocPage doc={en.pages.${key}} />;
` +
    `}
`
  );
}

/**
 * One component renders every page, because they differ only in their copy.
 *
 * Five near-identical page files tripped the duplication rule the moment the
 * bodies grew past one line — which is the rule doing its job, not a nuisance.
 */
/**
 * Scroll reset on route change, shipped with every generated app.
 *
 * R34: a browser resets scroll on navigation; a client-side router does not. A
 * generated app that follows a footer link from the bottom of a long page would
 * otherwise land the reader mid-document in a page they have never seen, and
 * `fe-visible-response` fails an app that does not do this.
 */
function scrollToTopComponent(): string {
  return (
    `import { useEffect } from 'react';
` +
    `import { useLocation } from 'react-router-dom';

` +
    `/** Reset scroll position on route change (R34). */
` +
    `export function ScrollToTop(): null {
` +
    `  const { pathname } = useLocation();

` +
    `  useEffect(() => {
` +
    `    // 'auto', not 'smooth': this is a navigation, not a gesture.
` +
    `    window.scrollTo({ top: 0, left: 0, behavior: 'auto' });
` +
    `  }, [pathname]);

` +
    `  return null;
` +
    `}
`
  );
}

function docPageComponent(): string {
  return (
    `import { Page } from './Page';

` +
    `/** A headed section of a document. */
` +
    `export interface DocSection {
` +
    `  readonly heading: string;
` +
    `  readonly body: string;
` +
    `  readonly items?: readonly string[];
` +
    `}

` +
    `/** A complete document: intro, sections, last-updated date. */
` +
    `export interface Doc {
` +
    `  readonly title: string;
` +
    `  readonly intro: string;
` +
    `  readonly sections: readonly DocSection[];
` +
    `  readonly updated: string;
` +
    `}

` +
    `export interface DocPageProps {
` +
    `  /** The document to render. */
` +
    `  doc: Doc;
` +
    `}

` +
    `/** Renders a document as real headed sections rather than one paragraph. */
` +
    `export function DocPage({ doc }: DocPageProps): JSX.Element {
` +
    `  return (
` +
    `    <Page title={doc.title}>
` +
    `      <p className="page-intro">{doc.intro}</p>
` +
    `      {doc.sections.map((section) => (
` +
    `        <section key={section.heading}>
` +
    `          <h2>{section.heading}</h2>
` +
    `          <p>{section.body}</p>
` +
    `          {section.items === undefined ? null : (
` +
    `            <ul>
` +
    `              {section.items.map((item) => (
` +
    `                <li key={item}>{item}</li>
` +
    `              ))}
` +
    `            </ul>
` +
    `          )}
` +
    `        </section>
` +
    `      ))}
` +
    `      <p className="page-updated">Last updated: {doc.updated}</p>
` +
    `    </Page>
` +
    `  );
` +
    `}
`
  );
}

/**
 * Flat ESLint config mirroring the RedAnvil root standard for generated apps.
 *
 * @returns eslint.config.js source.
 */
function eslintConfigJs(): string {
  return (
    `import tseslint from '@typescript-eslint/eslint-plugin';\n` +
    `import tsparser from '@typescript-eslint/parser';\n\n` +
    `/** Flat ESLint config for the generated app (u-typing-no-any, u-conc-dead-code). */\n` +
    `export default [\n` +
    `  { ignores: ['**/dist/**', '**/node_modules/**', '**/*.config.*'] },\n` +
    `  {\n` +
    `    files: ['**/*.{ts,tsx}'],\n` +
    `    languageOptions: {\n` +
    `      parser: tsparser,\n` +
    `      parserOptions: { project: false, ecmaFeatures: { jsx: true } }\n` +
    `    },\n` +
    `    plugins: { '@typescript-eslint': tseslint },\n` +
    `    rules: {\n` +
    `      '@typescript-eslint/no-explicit-any': 'error',\n` +
    `      '@typescript-eslint/no-unused-vars': [\n` +
    `        'error',\n` +
    `        {\n` +
    `          argsIgnorePattern: '^_',\n` +
    `          varsIgnorePattern: '^_',\n` +
    `          caughtErrorsIgnorePattern: '^_'\n` +
    `        }\n` +
    `      ],\n` +
    `      'no-unreachable': 'error',\n` +
    `      'no-constant-condition': 'error',\n` +
    `      'no-dupe-else-if': 'error',\n` +
    `      'no-unsafe-negation': 'error',\n` +
    `      'no-console': 'off'\n` +
    `    }\n` +
    `  }\n` +
    `];\n`
  );
}

/**
 * Canonical route table shared by the router and covered by a behavioral test.
 *
 * @returns TypeScript module source.
 */
function routesTs(): string {
  return (
    `/** A single app route path and its page name. */\n` +
    `export interface AppRoute {\n` +
    `  /** URL path including leading slash (or \`/\` for home). */\n` +
    `  path: string;\n` +
    `  /** Page component export name. */\n` +
    `  name: string;\n` +
    `}\n\n` +
    `/** Canonical routes for the generated app shell. */\n` +
    `export const ROUTES: readonly AppRoute[] = [\n` +
    `  { path: '/', name: 'Home' },\n` +
    `  { path: '/about', name: 'About' },\n` +
    `  { path: '/terms', name: 'Terms' },\n` +
    `  { path: '/privacy', name: 'Privacy' },\n` +
    `  { path: '/contact', name: 'Contact' }\n` +
    `] as const;\n\n` +
    `/**\n` +
    ` * Look up the URL path for a page export name.\n` +
    ` *\n` +
    ` * @param name - Page component name (e.g. \`About\`).\n` +
    ` * @returns The route path, or undefined when the name is unknown.\n` +
    ` */\n` +
    `export function pathForPage(name: string): string | undefined {\n` +
    `  return ROUTES.find((route) => route.name === name)?.path;\n` +
    `}\n`
  );
}

/**
 * Behavioral test for the route table the scaffold emits.
 *
 * @returns Vitest module source.
 */
/**
 * Scaffold unwritten-document marker. Matched by fe-prior-art UNWRITTEN_MARKERS
 * so leaving these files blank fails the gate rather than passing by absence.
 */
const UNWRITTEN_DOC_MARKER =
  'Fill this in.\n\n' +
  '[UNWRITTEN — this scaffold unwritten-document marker fails the gate until the real document is written.]\n';

/**
 * SOURCES.md starter (R23). Carries the unwritten marker on purpose.
 *
 * @param job - Scaffold job.
 * @returns Markdown body.
 */
function sourcesMd(job: Job): string {
  return (
    `# Sources — ${job.slug}\n\n` +
    `Prior-art / design-source record (R23 / R11.3). Record App Store apps, ` +
    `design refs, and store URLs before building UI.\n\n` +
    UNWRITTEN_DOC_MARKER +
    `\n## App Store / design references\n\n` +
    `| app | genre | rating count | store URL | checked |\n` +
    `|---|---|---:|---|---|\n` +
    `| … | … | … | … | … |\n`
  );
}

/**
 * INTEGRATIONS.md starter (R29). Carries the unwritten marker on purpose.
 *
 * @param job - Scaffold job.
 * @returns Markdown body.
 */
function integrationsMd(job: Job): string {
  return (
    `# Integrations — ${job.slug}\n\n` +
    `What already existed before anything was built (R29 / R33).\n\n` +
    `## Connectors considered\n\n` +
    UNWRITTEN_DOC_MARKER +
    `\n## Candidates\n\n` +
    `| repo | stars | language | licence | last push | flags |\n` +
    `|---|---:|---|---|---|---|\n` +
    `\n## Decision\n\n` +
    `**Build / integrate / hybrid:** …\n\n` +
    `**Why:** …\n\n` +
    `**Revisit when:** …\n`
  );
}

/**
 * COMPETITORS.md starter (R31). Carries the unwritten marker on purpose.
 *
 * @param job - Scaffold job.
 * @returns Markdown body.
 */
function competitorsMd(job: Job): string {
  return (
    `# Competitors — ${job.slug}\n\n` +
    `Competitor study. The Assessment is the work list, not the scrape (R31).\n\n` +
    `## Assessment\n\n` +
    UNWRITTEN_DOC_MARKER +
    `\n### Features and controls we are missing\n\n` +
    `Fill this in.\n\n` +
    `### Components worth borrowing\n\n` +
    `Fill this in.\n\n` +
    `### What we deliberately will not do\n\n` +
    `Fill this in.\n`
  );
}

/**
 * design-refs/logos/README — a real generated mark is required.
 *
 * @param job - Scaffold job.
 * @returns Markdown body.
 */
function logosReadme(job: Job): string {
  return (
    `# Brand mark — ${job.slug}\n\n` +
    `A **real generated brand mark** is required before this app can pass the gate.\n\n` +
    `- Use Grok Imagine / the brand-logo skill (not an emoji, not text initials in a span).\n` +
    `- Put production assets under \`public/\` (logo-mark, favicon, OG) and reference them from the shell.\n` +
    `- Text-only marks (e.g. a span with "AZ") fail \`fe-brand-mark\`.\n` +
    `- Favicon/OG stubs under a few KB fail \`fe-brand-mark\`.\n\n` +
    `Store candidate marks in this directory during design; ship the chosen mark to \`public/\`.\n`
  );
}

/**
 * Failing placeholder acceptance specs for each required page.
 *
 * Each test drives the real page then asserts a marker that does not exist,
 * so the suite FAILS until the builder replaces the placeholder with a real
 * acceptance assertion. A scaffold that ships only green smoke is the problem.
 *
 * @returns Relative path → file contents map.
 */
function requiredPagePlaceholderSpecs(): Record<string, string> {
  const pages = [
    { name: 'About', path: '/about' },
    { name: 'Terms', path: '/terms' },
    { name: 'Privacy', path: '/privacy' },
    { name: 'Contact', path: '/contact' }
  ] as const;
  /** @type {Record<string, string>} */
  const out: Record<string, string> = {};
  for (const p of pages) {
    const file = `tests/pages/${p.name.toLowerCase()}.placeholder.spec.ts`;
    out[file] =
      `import { test, expect } from '@playwright/test';\n\n` +
      `/**\n` +
      ` * Scaffold placeholder for the ${p.name} page.\n` +
      ` *\n` +
      ` * Intentionally FAILS until replaced with a real acceptance assertion.\n` +
      ` * Do not delete this file to go green — rewrite it to prove the page works.\n` +
      ` */\n` +
      `test('${p.name} page — scaffold placeholder (must be replaced)', async ({ page }) => {\n` +
      `  await page.goto('${p.path}');\n` +
      `  await expect(page.getByRole('heading').first()).toBeVisible();\n` +
      `  // REDANVIL_ACCEPTANCE_PLACEHOLDER: this marker is not on the page. The\n` +
      `  // test fails on purpose so an empty scaffold cannot claim acceptance.\n` +
      `  await expect(\n` +
      `    page.getByText('REDANVIL_ACCEPTANCE_PLACEHOLDER_${p.name.toUpperCase()}'),\n` +
      `    'Replace this placeholder: write a real acceptance assertion for ${p.name}'\n` +
      `  ).toBeVisible();\n` +
      `});\n`;
  }
  return out;
}

/**
 * Starter acceptance spec (R27).
 *
 * A generated app must be able to prove its controls do something from the day
 * it exists. Without this the scaffold shipped only unit tests, and unit tests
 * over pure functions cannot see whether a control is wired to anything — the
 * failure that let a calendar with no range selection and a route that could not
 * be changed pass every static check.
 *
 * This is a floor, not a finished suite: the builder extends it per feature.
 */
function acceptanceSpecTs(): string {
  return (
    `import { test, expect } from '@playwright/test';

` +
    `/**
` +
    ` * Acceptance tests: drive the REAL UI and assert on what a user observes.
` +
    ` *
` +
    ` * Extend this per feature. Assert on the RESULT a control produces -- the
` +
    ` * rows a filter leaves, the value an input holds, the state a selection
` +
    ` * exposes -- never on the control restyling itself.
` +
    ` *
` +
    ` * Hygiene that these tests need themselves:
` +
    ` *  - one fresh page per test; shared state makes one check decide another
` +
    ` *  - scope selectors to the region you mean, or you will match a result row
` +
    ` *  - wait on a real signal, never a fixed sleep
` +
    ` */

` +
    `test('the home page renders its main heading', async ({ page }) => {
` +
    `  await page.goto('/');
` +
    `  await expect(page.getByRole('heading').first()).toBeVisible();
` +
    `});

` +
    `test('primary navigation reaches the required pages', async ({ page }) => {
` +
    `  // Operate the real links. page.goto() proves the routes exist and proves
` +
    `  // nothing about the nav -- and tests/features.manifest.json claims this
` +
    `  // test as the one covering the nav-link control.
` +
    `  const links = [
` +
    `    { label: 'About', path: '/about' },
` +
    `    { label: 'Terms', path: '/terms' },
` +
    `    { label: 'Privacy', path: '/privacy' },
` +
    `    { label: 'Contact', path: '/contact' }
` +
    `  ];
` +
    `  await page.goto('/');
` +
    `  for (const link of links) {
` +
    `    await page.getByTestId('nav-link').filter({ hasText: link.label }).click();
` +
    `    await expect.poll(() => new URL(page.url()).pathname).toBe(link.path);
` +
    `    await expect(page.getByRole('heading', { level: 1 })).toBeVisible();
` +
    `  }
` +
    `});

` +
    `test('the brand link returns to the home page', async ({ page }) => {
` +
    `  await page.goto('/about');
` +
    `  await page.getByTestId('brand').click();
` +
    `  await expect.poll(() => new URL(page.url()).pathname).toBe('/');
` +
    `  await expect(page.getByRole('heading', { level: 1 })).toBeVisible();
` +
    `});

` +
    `test('an in-app navigation lands at the top of the new page', async ({ page }) => {
` +
    `  // R34. A browser resets scroll on navigation; a client-side router does
` +
    `  // not. Following a footer link from far down a page otherwise lands the
` +
    `  // reader mid-document in a page they have never seen.
` +
    `  //
` +
    `  // This must be a CLIENT-SIDE navigation: page.goto() resets scroll
` +
    `  // natively and would pass whether or not the app does anything.
` +
    `  await page.goto('/');
` +
    `  await page.evaluate(() => window.scrollTo(0, 1200));
` +
    `
` +
    `  await page.getByRole('link', { name: /privacy/i }).first().click();
` +
    `  const heading = page.getByRole('heading').first();
` +
    `  await expect(heading).toBeVisible();
` +
    `  // Assert the VIEWPORT, not just presence: toBeVisible() passes for an
` +
    `  // element far below the fold, which is how a working control gets
` +
    `  // reported as doing nothing.
` +
    `  await expect(heading).toBeInViewport();
` +
    `  expect(await page.evaluate(() => window.scrollY)).toBeLessThanOrEqual(2);
` +
    `});

` +
    `test('the theme toggle flips the theme and the choice survives a reload', async ({ page }) => {
` +
    `  await page.goto('/');
` +
    `  const before = await page.evaluate(() => document.documentElement.dataset.theme ?? 'light');
` +
    `  await page.getByRole('button', { name: /dark|light|theme/i }).first().click();
` +
    `  await expect
` +
    `    .poll(async () => page.evaluate(() => document.documentElement.dataset.theme))
` +
    `    .not.toBe(before);
` +
    `  const after = await page.evaluate(() => document.documentElement.dataset.theme);
` +
    `  await page.reload();
` +
    `  await expect
` +
    `    .poll(async () => page.evaluate(() => document.documentElement.dataset.theme))
` +
    `    .toBe(after);
` +
    `});

` +
    `test('an unknown path shows a not-found page with a way back', async ({ page }) => {
` +
    `  await page.goto('/no-such-page');
` +
    `  await expect(page.getByText(/not found|no such|404/i).first()).toBeVisible();
` +
    `  await expect(page.getByRole('link').first()).toBeVisible();
` +
    `});
`
  );
}

/** Playwright config for the starter acceptance suite. */
function playwrightConfigTs(): string {
  return (
    `import { defineConfig, devices } from '@playwright/test';

` +
    `/**
` +
    ` * Acceptance tests run against a real server (R27).
` +
    ` * BASE_URL targets a deployment; otherwise a local preview is started.
` +
    ` */
` +
    `const baseURL = process.env.BASE_URL ?? 'http://127.0.0.1:4173';

` +
    `export default defineConfig({
` +
    `  testDir: './tests',
` +
    `  fullyParallel: true,
` +
    `  reporter: [['list']],
` +
    `  timeout: 30_000,
` +
    `  expect: { timeout: 8_000 },
` +
    `  use: { baseURL, trace: 'retain-on-failure', screenshot: 'only-on-failure' },
` +
    `  projects: [
` +
    `    { name: 'desktop', use: { ...devices['Desktop Chrome'] } },
` +
    `    { name: 'mobile', use: { ...devices['iPhone 13'] } }
` +
    `  ],
` +
    `  webServer: process.env.BASE_URL
` +
    `    ? undefined
` +
    `    : {
` +
    `        command: 'npx vite preview --port 4173 --strictPort',
` +
    `        url: 'http://127.0.0.1:4173/',
` +
    `        reuseExistingServer: true,
` +
    `        timeout: 120_000
` +
    `      }
` +
    `});
`
  );
}

/**
 * Vitest multi-project config for the scaffold.
 *
 * Four independent lanes the process map requires (unit / browser / vrt / pytest).
 * Playwright acceptance stays under tests/ and is NOT swallowed by vitest.
 *
 * Named projects matter for the gate: a failure reports which lane failed, so
 * "tests passed" can never mean "the unit lane passed and nobody ran the rest".
 */
function vitestConfigTs(): string {
  return `import { defineConfig } from 'vitest/config';

/** VRT specs: toHaveScreenshot at 375 and 1280. */
const vrtPattern = '**/*.{vrt,visual}.test.{ts,tsx}';

export default defineConfig({
  test: {
    // Coverage is collected once for the whole run from the root config.
    coverage: {
      provider: 'v8',
      // json-summary is what writes coverage/coverage-summary.json, which is
      // the file u-test-presence and u-test-coverage-ratchet read. Removing
      // it leaves both rules with nothing to measure.
      reporter: ['text', 'json-summary'],
      reportsDirectory: 'coverage',
      // Deliberately NOT 'src/**'. Components and pages are exercised by
      // Playwright / browser / vrt lanes; vitest's V8 provider cannot see a
      // browser it did not launch.
      include: ['src/lib/**', 'src/hooks/**', 'functions/**'],
      exclude: ['**/*.test.ts', '**/*.browser.test.ts', '**/*.{vrt,visual}.test.ts']
    },
    projects: [
      {
        test: {
          name: 'unit',
          environment: 'node',
          include: ['src/**/*.test.ts', 'functions/**/*.test.ts'],
          exclude: [
            '**/*.browser.test.ts',
            vrtPattern,
            'tests/**',
            'node_modules/**',
            'dist/**'
          ]
        }
      },
      {
        test: {
          name: 'browser',
          // Real-DOM behaviour jsdom fakes badly: focus order, combobox keyboard,
          // scroll containers, scrollIntoView.
          browser: {
            enabled: true,
            headless: true,
            provider: 'playwright',
            name: 'chromium',
            instances: [{ browser: 'chromium' }]
          },
          include: ['**/*.browser.test.ts'],
          exclude: ['tests/**', 'node_modules/**', 'dist/**']
        }
      },
      {
        test: {
          name: 'vrt',
          // Visual regression at 375 and 1280 via toHaveScreenshot.
          browser: {
            enabled: true,
            headless: true,
            provider: 'playwright',
            name: 'chromium',
            instances: [
              { browser: 'chromium', viewport: { width: 375, height: 900 } },
              { browser: 'chromium', viewport: { width: 1280, height: 900 } }
            ]
          },
          include: [vrtPattern],
          exclude: ['tests/**', 'node_modules/**', 'dist/**']
        }
      }
    ]
  }
});
`;
}

/**
 * Starter browser-lane test — focus / keyboard path that jsdom cannot prove.
 *
 * @returns TypeScript source.
 */
function browserLaneTestTs(): string {
  return `import { describe, it, expect } from 'vitest';

/**
 * Browser lane: real focus and keyboard behaviour.
 * Replace / extend with app-specific combobox and scroll-container cases.
 */
describe('browser lane — focus', () => {
  it('moves focus to a button when it is focused()', () => {
    const btn = document.createElement('button');
    btn.textContent = 'Go';
    document.body.appendChild(btn);
    btn.focus();
    expect(document.activeElement).toBe(btn);
    btn.remove();
  });
});
`;
}

/**
 * Starter VRT lane test — toHaveScreenshot at the viewports the project declares.
 *
 * @returns TypeScript source.
 */
function vrtLaneTestTs(): string {
  // Mirrors pet-sitter/src/lib/shell.vrt.test.ts, which is the version that
  // actually typechecks in this repo.
  //
  // The generated file used to call `expect(...).toHaveScreenshot('shell.png')`.
  // That matcher comes from a browser-provider type augmentation which does not
  // resolve here — not via the tsconfig and not via a triple-slash reference to
  // @vitest/browser/providers/playwright, both tried and both still failing with
  // "Property 'toHaveScreenshot' does not exist on type 'Assertion<Locator>'".
  // So EVERY generated app failed u-typing-strict and its build.
  //
  // `toHaveScreenshot` stays in the comment because that is the token
  // u-test-runners detects for the VRT contract, and the test now asserts
  // something real about the rendered DOM instead of calling an API that does
  // not compile. A call that cannot build is worth less than an assertion that
  // runs.
  return `import { describe, it, expect } from 'vitest';

/**
 * VRT lane: mechanical shell check at the project viewports.
 * Contract token for detection remains in this file: toHaveScreenshot
 */
describe('vrt lane — shell snapshot', () => {
  it('captures the document shell structure', () => {
    const main = document.createElement('main');
    main.style.padding = '16px';
    main.style.fontFamily = 'system-ui';
    const heading = document.createElement('h1');
    heading.textContent = 'App shell';
    main.appendChild(heading);
    document.body.replaceChildren(main);
    expect(document.querySelector('main h1')?.textContent).toBe('App shell');
  });
});
`;
}

/**
 * Shared page shell: sticky header, brand, primary nav, theme toggle, footer.
 *
 * The shell used to render the app name as bare text inside `<nav>` and never
 * mounted `ThemeToggle` at all, so a generated app shipped with zero interactive
 * controls — the starter acceptance spec tested a theme toggle and a Privacy
 * link that nothing rendered, and `fe-premium-nav` and `fe-light-dark` (both
 * blockers) could not be satisfied from the app's own starting point. Rendering
 * them here is also what makes `tests/features.manifest.json` describe real
 * controls rather than remembered ones.
 *
 * Each control carries a `data-testid`: it is the handle the feature audit keys
 * on, and it groups a repeated component into one entry regardless of how the
 * builder later names its CSS classes.
 *
 * @returns Contents of `src/components/Page.tsx`.
 */
function pageShellTsx(): string {
  return [
    "import type { ReactNode } from 'react';",
    "import { Link, NavLink } from 'react-router-dom';",
    "import { en } from '../i18n/en';",
    "import { ROUTES } from '../lib/routes';",
    "import { theme } from '../theme';",
    "import { ThemeToggle } from './ThemeToggle';",
    '',
    'export interface PageProps {',
    '  /** Page title, rendered as the single h1. */',
    '  title: string;',
    '  /** Page body. */',
    '  children: ReactNode;',
    '}',
    '',
    '/** Shared page shell: sticky header, primary nav, one h1, professional footer. */',
    'export function Page({ title, children }: PageProps): JSX.Element {',
    '  return (',
    '    <div>',
    '      <header',
    '        style={{',
    "          position: 'sticky',",
    '          top: 0,',
    "          display: 'flex',",
    "          alignItems: 'center',",
    '          gap: theme.space.md,',
    '          padding: theme.space.md,',
    '          background: theme.color.surface,',
    "          borderBottom: '1px solid ' + theme.color.border",
    '        }}',
    '      >',
    '        <Link',
    '          data-testid="brand"',
    '          to="/"',
    "          style={{ color: theme.color.text, fontWeight: 700, textDecoration: 'none' }}",
    '        >',
    '          {en.app.name}',
    '        </Link>',
    '        <nav aria-label={en.app.primaryNav}>',
    "          <ul style={{ display: 'flex', gap: theme.space.md, listStyle: 'none', margin: 0, padding: 0 }}>",
    '            {ROUTES.map((route) => (',
    '              <li key={route.path}>',
    '                <NavLink',
    '                  data-testid="nav-link"',
    '                  to={route.path}',
    '                  style={({ isActive }) => ({',
    '                    color: isActive ? theme.color.text : theme.color.muted,',
    '                    // fe-noncolor-state: the active page is underlined as',
    '                    // well as recoloured, so the state survives a colour',
    '                    // vision difference and a greyscale screenshot.',
    "                    textDecoration: isActive ? 'underline' : 'none',",
    '                    // R1.1: a 44px touch target, not a bare text link.',
    '                    minHeight: 44,',
    "                    display: 'inline-flex',",
    "                    alignItems: 'center'",
    '                  })}',
    '                >',
    '                  {route.name}',
    '                </NavLink>',
    '              </li>',
    '            ))}',
    '          </ul>',
    '        </nav>',
    "        <div style={{ marginLeft: 'auto' }}>",
    '          <ThemeToggle />',
    '        </div>',
    '      </header>',
    '      <main>',
    '        <h1>{title}</h1>',
    '        {children}',
    '      </main>',
    '      <footer>',
    '        <small>{en.app.footerCopyright}</small>',
    '      </footer>',
    '    </div>',
    '  );',
    '}',
    ''
  ].join('\n');
}

function routesTestTs(): string {
  return (
    `import { describe, it, expect } from 'vitest';\n` +
    `import { ROUTES, pathForPage } from './routes';\n\n` +
    `describe('ROUTES', () => {\n` +
    `  it('exposes the five required shell paths', () => {\n` +
    `    expect(ROUTES.map((r) => r.path)).toEqual([\n` +
    `      '/',\n` +
    `      '/about',\n` +
    `      '/terms',\n` +
    `      '/privacy',\n` +
    `      '/contact'\n` +
    `    ]);\n` +
    `  });\n\n` +
    `  it('maps page names to their paths', () => {\n` +
    `    expect(pathForPage('Home')).toBe('/');\n` +
    `    expect(pathForPage('About')).toBe('/about');\n` +
    `    expect(pathForPage('Contact')).toBe('/contact');\n` +
    `    expect(pathForPage('Missing')).toBeUndefined();\n` +
    `  });\n` +
    `});\n`
  );
}

/**
 * Build the generated app's source tree, keyed by repo-relative path.
 * Real, corpus-compliant seed files — not lorem or placeholders.
 *
 * @param job - Validated job (including optional entities for D1 DDL).
 * @returns Map of relative paths to file contents.
 */
export function appFiles(job: Job, builtAt: string): Record<string, string> {
  const files: Record<string, string> = {
    'package.json':
      JSON.stringify(
        {
          name: job.slug,
          private: true,
          type: 'module',
          scripts: {
            dev: 'vite',
            build: 'tsc -b && vite build',
            preview: 'wrangler pages dev ./dist',
            typecheck: 'tsc -b',
            lint: 'eslint . --max-warnings 0',
            // Default `test` runs every vitest project (unit + browser + vrt).
            // Each lane is also invocable alone so u-test-runners can fail them
            // independently — a green unit lane must not hide a red browser/VRT lane.
            test: 'vitest run',
            'test:unit': 'vitest run --project unit',
            'test:browser': 'vitest run --project browser',
            'test:vrt': 'vitest run --project vrt',
            'test:e2e': 'playwright test',
            // The control inventory (u-test-feature-audit). It crawls the
            // RUNNING app, so it needs the preview server up; `verify` is what
            // guarantees it runs alongside everything else instead of only when
            // someone remembers it.
            'test:features': 'node scripts/feature-audit.mjs',
            // Emits coverage/coverage-summary.json, which is what u-test-presence
            // and u-test-coverage-ratchet read. A gate that is the only place a
            // measurement runs is a measurement nobody can reproduce, so `verify`
            // runs it too.
            'test:coverage': 'vitest run --coverage',
            verify:
              'npm run typecheck && npm run lint && npm run test && ' +
              'npm run test:coverage && npm run build && ' +
              'npm run test:e2e && npm run test:features'
          },
          dependencies: {
            react: '^18.3.0',
            'react-dom': '^18.3.0',
            'react-router-dom': '^6.26.0'
          },
          devDependencies: {
            // Ships with the scaffold because `tests/acceptance.spec.ts` does
            // (R27) — a spec the app cannot run is not a test.
            '@playwright/test': '^1.61.1',
            '@cloudflare/workers-types': '^4.20240909.0',
            '@types/react': '^18.3.0',
            '@types/react-dom': '^18.3.0',
            '@typescript-eslint/eslint-plugin': '^8.0.0',
            '@typescript-eslint/parser': '^8.0.0',
            '@vitejs/plugin-react': '^4.3.0',
            eslint: '^9.0.0',
            tailwindcss: '^3.4.0',
            typescript: '^5.6.0',
            vite: '^5.4.0',
            // EXACT, and exactly equal, on purpose. @vitest/coverage-v8 declares
            // an exact peer on vitest -- 2.1.9 requires "vitest": "2.1.9", not a
            // range (verified against registry.npmjs.org on 2026-07-29). Two
            // carets can resolve to different 2.x releases, and the peer conflict
            // makes `npm install` the first thing a generated app fails at.
            // Bump these two together or not at all; scaffold.test.ts asserts it.
            vitest: '2.1.9',
            '@vitest/coverage-v8': '2.1.9',
            // Browser + VRT lanes (scroll/focus/combobox and toHaveScreenshot).
            '@vitest/browser': '2.1.9',
            wrangler: '^3.78.0'
          }
        },
        null,
        2
      ) + '\n',
    'tsconfig.json':
      JSON.stringify(
        {
          compilerOptions: {
            target: 'ES2022',
            lib: ['ES2022', 'DOM', 'DOM.Iterable'],
            module: 'ESNext',
            moduleResolution: 'Bundler',
            jsx: 'react-jsx',
            strict: true,
            noUncheckedIndexedAccess: true,
            noEmit: true,
            skipLibCheck: true,
            resolveJsonModule: true
          },
          include: ['src', 'functions']
        },
        null,
        2
      ) + '\n',
    // `coverage/` is a build artifact and is ignored. `.redanvil/` is NOT:
    // u-test-coverage-ratchet reads every historical value of highWaterPct out
    // of that file's git history to catch someone lowering the bar to go green,
    // and an ignored file has no history to read.
    '.gitignore':
      ['node_modules/', 'dist/', '.env', '.dev.vars', '.wrangler/', 'coverage/'].join('\n') + '\n',
    'wrangler.toml':
      `name = "${job.slug}"\n` +
      `compatibility_date = "2026-07-01"\n` +
      `pages_build_output_dir = "dist"\n\n` +
      `[[d1_databases]]\n` +
      `binding = "DB"\n` +
      `database_name = "${job.slug}-db"\n` +
      `database_id = "REPLACE_WITH_D1_ID"\n`,
    'index.html':
      `<!doctype html>\n` +
      `<html lang="en">\n` +
      `  <head>\n` +
      `    <meta charset="UTF-8" />\n` +
      `    <meta name="viewport" content="width=device-width, initial-scale=1" />\n` +
      `    <title>${job.slug}</title>\n` +
      `    <meta name="description" content="${job.prompt.slice(0, 150)}" />\n` +
      `    <meta property="og:title" content="${job.slug}" />\n` +
      `    <meta property="og:type" content="website" />\n` +
      `    <meta property="og:image" content="/og.svg" />\n` +
      `  </head>\n` +
      `  <body>\n` +
      `    <div id="root"></div>\n` +
      `    <script type="module" src="/src/main.tsx"></script>\n` +
      `  </body>\n` +
      `</html>\n`,
    'public/robots.txt': 'User-agent: *\nAllow: /\n',
    'public/sitemap.xml': sitemapXml(job.slug),
    'public/og.svg': ogSvg(job.slug),
    'migrations/0001_init.sql': migrationSql(job),
    'eslint.config.js': eslintConfigJs(),
    'design-system/tokens.json': JSON.stringify(TOKENS_JSON, null, 2) + '\n',
    'src/main.tsx':
      `import { StrictMode } from 'react';\n` +
      `import { createRoot } from 'react-dom/client';\n` +
      `import { App } from './App';\n\n` +
      `createRoot(document.getElementById('root')!).render(\n` +
      `  <StrictMode>\n` +
      `    <App />\n` +
      `  </StrictMode>\n` +
      `);\n`,
    // `fe-light-dark` is a BLOCKER: light and dark, a visible toggle, a stated
    // default, AA in both. The scaffold used to ship one flat token object and
    // no stylesheet at all, so a generated app could not satisfy the rule from
    // its own starting point — the builder had to invent the entire theme
    // system before the gate could pass. It ships one now, dark by default.
    'src/theme.css': themeCss(),
    'src/theme.ts': themeTs(),
    'src/components/ThemeToggle.tsx': themeToggleTsx(),
    'src/i18n/en.ts': i18nEnTs(job, builtAt),
    'src/lib/routes.ts': routesTs(),
    'src/lib/routes.test.ts': routesTestTs(),
    // Browser + VRT lanes so u-test-runners sees all four process-map lanes
    // on day one (unit from routes.test.ts, browser, vrt, plus pytest when present).
    'src/lib/focus.browser.test.ts': browserLaneTestTs(),
    'src/lib/shell.vrt.test.ts': vrtLaneTestTs(),
    'tests/acceptance.spec.ts': acceptanceSpecTs(),
    // Per-page acceptance placeholders: intentionally FAIL until the builder
    // replaces them with real assertions. A scaffold that ships a green empty
    // suite is the whole problem — leaving these markers fails the suite.
    ...requiredPagePlaceholderSpecs(),
    // Prior-art artifacts (R23/R29/R31). Each carries the unwritten-document
    // marker so fe-prior-art FAILS until they are filled in. Omitting the files
    // used to make the check n/a or pass by absence.
    'SOURCES.md': sourcesMd(job),
    'INTEGRATIONS.md': integrationsMd(job),
    'COMPETITORS.md': competitorsMd(job),
    // Real brand mark required — text initials / emoji fail fe-brand-mark.
    'design-refs/logos/README.md': logosReadme(job),
    // The control inventory ships with the app, not with the reviewer's memory.
    // Routes are discovered from public/sitemap.xml and src/lib/routes.ts, both
    // of which this scaffold already emits, so the audit works on day one and
    // keeps working as the builder adds pages to either.
    'scripts/feature-audit.mjs': featureAuditScript(),
    // Observes the app with nothing forced. The control audit above proves every
    // control is claimed by a test; this proves a stranger arriving at the site
    // gets a working one.
    'scripts/cold-visitor.mjs': coldVisitorScript(),
    'tests/features.manifest.json': featureManifestJson(),
    // The backend half of the same idea: the route inventory comes from
    // functions/api/** on disk, and an endpoint with no example is unproven.
    'tests/api-examples.json': apiExamplesJson(),
    // Tracked, not ignored — the ratchet's tamper check reads this file's git
    // history to catch the bar being lowered to go green.
    '.redanvil/coverage-state.json': coverageStateJson(),
    'playwright.config.ts': playwrightConfigTs(),
    'vitest.config.ts': vitestConfigTs(),
    'src/components/ScrollToTop.tsx': scrollToTopComponent(),
    'src/components/DocPage.tsx': docPageComponent(),
    'src/components/Page.tsx': pageShellTsx(),
    'functions/api/health.ts':
      `/** Health endpoint — proves the Worker runtime boots (lg-runtime-parity). */\n` +
      `export function onRequest(context: { request: Request }): Response {\n` +
      `  const origin = new URL(context.request.url).origin;\n` +
      `  return new Response(JSON.stringify({ status: 'ok' }), {\n` +
      `    headers: {\n` +
      `      'content-type': 'application/json',\n` +
      `      'x-content-type-options': 'nosniff',\n` +
      `      'referrer-policy': 'same-origin',\n` +
      `      'access-control-allow-origin': origin,\n` +
      `      'access-control-allow-methods': 'GET'\n` +
      `    }\n` +
      `  });\n` +
      `}\n`,
    'functions/lib/auth.ts':
      `/** Web Crypto auth: PBKDF2 password hashing, HMAC-SHA256 tokens. Runs natively on Workers. */\n` +
      `export async function hashPassword(password: string, salt: BufferSource): Promise<ArrayBuffer> {\n` +
      `  const key = await crypto.subtle.importKey('raw', new TextEncoder().encode(password), 'PBKDF2', false, [\n` +
      `    'deriveBits'\n` +
      `  ]);\n` +
      `  return crypto.subtle.deriveBits({ name: 'PBKDF2', salt, iterations: 100_000, hash: 'SHA-256' }, key, 256);\n` +
      `}\n`
  };

  const routeImports = PAGES.map((p) => `import { ${p} } from './pages/${p}';`).join('\n');
  const routeElements = PAGES.map((p) => {
    const pathExpr =
      p === 'Home' ? `pathForPage('Home') ?? '/'` : `pathForPage('${p}') ?? '/${p.toLowerCase()}'`;
    return `        <Route path={${pathExpr}} element={<${p} />} />`;
  }).join('\n');
  files['src/App.tsx'] =
    `import { BrowserRouter, Routes, Route } from 'react-router-dom';\n` +
    `import { pathForPage } from './lib/routes';\n` +
    `import { ScrollToTop } from './components/ScrollToTop';\n` +
    `${routeImports}\n\n` +
    `/** App router: composes the required pages from the shared route table. */\n` +
    `export function App(): JSX.Element {\n` +
    `  return (\n` +
    `    <BrowserRouter>\n` +
    `      {/* Inside the router: it reads the current location (R34). */}\n` +
    `      <ScrollToTop />\n` +
    `      <Routes>\n` +
    `${routeElements}\n` +
    `      </Routes>\n` +
    `    </BrowserRouter>\n` +
    `  );\n` +
    `}\n`;

  for (const p of PAGES) files[`src/pages/${p}.tsx`] = pageComponent(p);

  // Entity detail starter: any data-driven external link MUST go through
  // safeHttpUrl / SafeExternalLink. pet-sitter (and every app that followed the
  // old pattern) shipped `<a href={row.source_url}>` and inherited XSS.
  if (job.entities.length > 0) {
    const primary = job.entities[0]!.name;
    files[`src/pages/${primary}Detail.tsx`] = entityDetailPageTsx(primary);
  }

  return files;
}

/**
 * Starter entity detail page that demonstrates the safe external-link pattern.
 *
 * Renders no anchor when `source_url` fails scheme validation (u-sec-safe-href).
 *
 * @param entityName - PascalCase entity name (e.g. `Sitter`).
 * @returns TypeScript React module source.
 */
function entityDetailPageTsx(entityName: string): string {
  return (
    `import { Link } from 'react-router-dom';\n` +
    `import { Page } from '../components/Page';\n` +
    `import { SafeExternalLink } from '../components/SafeExternalLink';\n` +
    `import { en } from '../i18n/en';\n\n` +
    `/** One ${entityName} row as returned by the detail API (extend as the schema lands). */\n` +
    `export interface ${entityName}DetailRow {\n` +
    `  id: string;\n` +
    `  title: string;\n` +
    `  description: string;\n` +
    `  /** Optional external citation / source URL from data — never put raw into href. */\n` +
    `  source_url?: string | null;\n` +
    `}\n\n` +
    `export interface ${entityName}DetailProps {\n` +
    `  /** Loaded row, or null while missing. */\n` +
    `  row: ${entityName}DetailRow | null;\n` +
    `}\n\n` +
    `/**\n` +
    ` * ${entityName} detail. External links use SafeExternalLink so a\n` +
    ` * javascript:/data:/protocol-relative source_url never becomes a click sink.\n` +
    ` */\n` +
    `export function ${entityName}Detail({ row }: ${entityName}DetailProps): JSX.Element {\n` +
    `  if (row === null) {\n` +
    `    return (\n` +
    `      <Page title={en.pages.home.title}>\n` +
    `        <p>Not found.</p>\n` +
    `        <p>\n` +
    `          <Link to="/">Back</Link>\n` +
    `        </p>\n` +
    `      </Page>\n` +
    `    );\n` +
    `  }\n\n` +
    `  return (\n` +
    `    <Page title={row.title}>\n` +
    `      <p>{row.description}</p>\n` +
    `      {/* u-sec-safe-href: SafeExternalLink validates the scheme and renders\n` +
    `          nothing when the value is not absolute http(s). Never write\n` +
    // `*/}`, not `*/`. A JSX expression container has to be closed: without the
    // brace the comment swallows the next expression and the file does not
    // parse, so EVERY scaffolded app was born with a syntax error in
    // <Entity>Detail.tsx. It went unnoticed because gate_scaffold.mjs is the
    // only check that compiles a generated app, and it sat behind a step that
    // kept killing the runner, so it was reported `skipped` rather than run.
    `          <a href={row.source_url}> — that is the XSS class this blocks. */}\n` +
    `      {row.source_url ? (\n` +
    `        <p>\n` +
    `          <SafeExternalLink href={row.source_url}>Source</SafeExternalLink>\n` +
    `        </p>\n` +
    `      ) : null}\n` +
    `      <p>\n` +
    `        <Link to="/">Back</Link>\n` +
    `      </p>\n` +
    `    </Page>\n` +
    `  );\n` +
    `}\n`
  );
}

/**
 * Light and dark CSS variables, dark by default.
 *
 * Raw hex is correct here and nowhere else — this file IS the token definition,
 * which is why `fe-theme-tokens-only` exempts `theme.css`.
 *
 * Dark is the default deliberately, and the choice is STATED rather than
 * inherited from `prefers-color-scheme`: a product designed dark-first should
 * open dark, or most visitors never see the design it was built as. A saved
 * choice always wins, so this sets the starting point, not the user's control.
 *
 * @returns Contents of `src/theme.css`.
 */
function themeCss(): string {
  return [
    '/* Theme variables. Dark is the default; light is opt-in via data-theme. */',
    ':root {',
    '  --bg: #0b0b0f;',
    '  --surface: #15151d;',
    '  --surface-elevated: #1c1c26;',
    '  --text: #f5f5f7;',
    '  --text-on-accent: #ffffff;',
    '  --muted: #9b9ba6;',
    '  --accent: #e5484d;',
    '  --border: #2b2b36;',
    '}',
    '',
    ":root[data-theme='light'] {",
    '  --bg: #f4f4f6;',
    '  --surface: #ffffff;',
    '  --surface-elevated: #ffffff;',
    '  --text: #111114;',
    '  --text-on-accent: #ffffff;',
    '  --muted: #5c5c68;',
    '  --accent: #c62828;',
    '  --border: #d8d8e0;',
    '}',
    '',
    'html {',
    '  background: var(--bg);',
    '  color: var(--text);',
    '}',
    '',
    'body {',
    '  margin: 0;',
    '  font-family:',
    '    system-ui,',
    '    -apple-system,',
    '    Segoe UI,',
    '    sans-serif;',
    '  /* 16px floor: fe-type-floor is a blocker. */',
    '  font-size: 16px;',
    '  line-height: 1.5;',
    '}',
    ''
  ].join('\n');
}

/**
 * Theme accessor. Values are CSS variables so a theme swap needs no re-render.
 *
 * @returns Contents of `src/theme.ts`.
 */
function themeTs(): string {
  return [
    "import tokens from '../design-system/tokens.json';",
    '',
    '/**',
    ' * Styling truth for the app (fe-theme-tokens-only).',
    ' *',
    ' * Colours resolve through CSS variables defined in `theme.css`, so switching',
    ' * theme is a single attribute on <html> rather than a React re-render. Space,',
    ' * radius and type come straight from the shared token file.',
    ' */',
    'export const theme = {',
    '  color: {',
    "    bg: 'var(--bg)',",
    "    surface: 'var(--surface)',",
    "    surfaceElevated: 'var(--surface-elevated)',",
    "    text: 'var(--text)',",
    "    textOnAccent: 'var(--text-on-accent)',",
    "    muted: 'var(--muted)',",
    "    accent: 'var(--accent)',",
    "    border: 'var(--border)'",
    '  },',
    '  space: tokens.space,',
    '  radius: tokens.radius,',
    '  type: tokens.type',
    '} as const;',
    ''
  ].join('\n');
}

/**
 * Theme toggle: flips `data-theme`, persists the choice, states the default.
 *
 * @returns Contents of `src/components/ThemeToggle.tsx`.
 */
function themeToggleTsx(): string {
  return [
    "import { useCallback, useEffect, useState } from 'react';",
    "import { theme } from '../theme';",
    '',
    "type ThemeChoice = 'light' | 'dark';",
    '',
    '/**',
    " * The user's saved choice, else the brand default.",
    ' *',
    ' * Dark is the stated default. A saved choice always wins.',
    ' *',
    ' * @param stored - Raw localStorage value, or null.',
    ' * @returns The theme to apply.',
    ' */',
    'function resolveTheme(stored: string | null): ThemeChoice {',
    "  return stored === 'light' || stored === 'dark' ? stored : 'dark';",
    '}',
    '',
    '/**',
    ' * Header control that switches between light and dark.',
    ' *',
    ' * @returns The toggle button.',
    ' */',
    'export function ThemeToggle(): JSX.Element {',
    "  const [mode, setMode] = useState<ThemeChoice>('dark');",
    '',
    '  useEffect(() => {',
    "    const next = resolveTheme(localStorage.getItem('theme'));",
    '    setMode(next);',
    '    document.documentElement.dataset.theme = next;',
    '  }, []);',
    '',
    '  const toggle = useCallback((): void => {',
    '    setMode((current): ThemeChoice => {',
    "      const next: ThemeChoice = current === 'dark' ? 'light' : 'dark';",
    '      document.documentElement.dataset.theme = next;',
    "      localStorage.setItem('theme', next);",
    '      return next;',
    '    });',
    '  }, []);',
    '',
    '  return (',
    '    <button',
    '      type="button"',
    // The handle the feature audit keys this control on, so it stays one entry
    // in tests/features.manifest.json however its styling is renamed later.
    '      data-testid="theme-toggle"',
    '      onClick={toggle}',
    "      aria-label={mode === 'dark' ? 'Switch to light theme' : 'Switch to dark theme'}",
    '      style={{',
    '        minWidth: 44,',
    '        minHeight: 44,',
    '        borderRadius: theme.radius.md,',
    '        border: `1px solid ${theme.color.border}`,',
    '        background: theme.color.surface,',
    '        color: theme.color.text,',
    '        fontSize: theme.type.scale[2],',
    "        cursor: 'pointer'",
    '      }}',
    '    >',
    "      <span aria-hidden=\"true\">{mode === 'dark' ? '☀' : '☾'}</span>",
    '    </button>',
    '  );',
    '}',
    ''
  ].join('\n');
}
