import type { Job } from '../schemas/job';

const PAGES = ['Home', 'About', 'Terms', 'Privacy', 'Contact'] as const;

/** Map scaffold field types to SQLite column types. */
const SQL_TYPE: Record<'text' | 'integer' | 'real' | 'blob', string> = {
  text: 'TEXT',
  integer: 'INTEGER',
  real: 'REAL',
  blob: 'BLOB'
};

/** Design tokens shipped inside the generated app (single source for theme). */
const TOKENS_JSON = {
  version: '1.0.0',
  color: {
    bg: '#0b0b0f',
    surface: '#15151d',
    text: '#f5f5f7',
    accent: '#e5484d',
    muted: '#8b8b93',
    border: '#26263049'
  },
  space: { xs: 4, sm: 8, md: 16, lg: 24, xl: 40 },
  radius: { sm: 6, md: 12, lg: 20 },
  type: { scale: [12, 14, 16, 20, 28, 40], family: 'Inter, system-ui, sans-serif' }
} as const;

/**
 * Convert a PascalCase / camelCase entity name to a snake_case SQL table name.
 *
 * @param name - Entity name matching Job.entities[].name.
 * @returns Lowercase snake_case table identifier.
 */
function entityToTableName(name: string): string {
  const snake = name
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .replace(/[^A-Za-z0-9_]+/g, '_')
    .toLowerCase();
  // SQLite unquoted identifiers cannot start with a digit.
  return /^[0-9]/.test(snake) ? `t_${snake}` : snake.length > 0 ? snake : 'items';
}

/**
 * Derive a SQL-safe table name from a kebab-case app slug when no entities exist.
 *
 * @param slug - Job slug (e.g. `demo-app`).
 * @returns Snake_case table name (e.g. `demo_app`).
 */
function slugToTableName(slug: string): string {
  const snake = slug.replace(/-/g, '_').replace(/[^a-z0-9_]/g, '');
  if (snake.length === 0) return 'app_items';
  return /^[0-9]/.test(snake) ? `app_${snake}` : snake;
}

/**
 * Build `migrations/0001_init.sql` from job entities, or a slug-derived table when empty.
 *
 * @param job - Validated scaffold job.
 * @returns SQL text with at least one CREATE TABLE statement.
 */
function migrationSql(job: Job): string {
  const entities =
    job.entities.length > 0
      ? job.entities
      : [
          {
            name: slugToTableName(job.slug),
            fields: [] as { name: string; type: 'text' | 'integer' | 'real' | 'blob' }[]
          }
        ];

  const blocks = entities.map((entity) => {
    const table = entityToTableName(entity.name);
    const fieldLines = entity.fields.map((field) => `  ${field.name} ${SQL_TYPE[field.type]},`);
    const cols = [
      '  id INTEGER PRIMARY KEY AUTOINCREMENT,',
      ...fieldLines,
      '  created_at TEXT NOT NULL'
    ].join('\n');
    return `CREATE TABLE IF NOT EXISTS ${table} (\n${cols}\n);`;
  });

  return (
    `-- Initial D1 schema for ${job.slug}.\n` +
    `-- Generated by RedAnvil scaffold; apply with wrangler d1 migrations apply.\n\n` +
    blocks.join('\n\n') +
    '\n'
  );
}

/**
 * Self-contained SVG Open Graph card for the generated app.
 *
 * @param slug - App slug rendered on the card.
 * @returns SVG markup.
 */
function ogSvg(slug: string): string {
  const safe = slug
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
  return (
    `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630" role="img" aria-label="${safe}">\n` +
    `  <rect width="1200" height="630" fill="#0b0b0f"/>\n` +
    `  <rect x="48" y="48" width="1104" height="534" rx="24" fill="#15151d" stroke="#262630" stroke-width="2"/>\n` +
    `  <text x="96" y="280" fill="#f5f5f7" font-family="Inter, system-ui, sans-serif" font-size="64" font-weight="700">${safe}</text>\n` +
    `  <text x="96" y="360" fill="#8b8b93" font-family="Inter, system-ui, sans-serif" font-size="32">Built with RedAnvil</text>\n` +
    `</svg>\n`
  );
}

/**
 * XML sitemap listing the five required app routes.
 *
 * @param slug - App slug used as the pages.dev host prefix.
 * @returns Sitemap XML.
 */
function sitemapXml(slug: string): string {
  const origin = `https://${slug}.pages.dev`;
  const paths = ['/', '/about', '/terms', '/privacy', '/contact'] as const;
  const urls = paths
    .map((path) => {
      const loc = path === '/' ? `${origin}/` : `${origin}${path}`;
      const priority =
        path === '/' ? '1.0' : path === '/about' || path === '/contact' ? '0.6' : '0.3';
      const changefreq =
        path === '/' ? 'weekly' : path === '/about' || path === '/contact' ? 'monthly' : 'yearly';
      return (
        `  <url>\n` +
        `    <loc>${loc}</loc>\n` +
        `    <changefreq>${changefreq}</changefreq>\n` +
        `    <priority>${priority}</priority>\n` +
        `  </url>`
      );
    })
    .join('\n');
  return (
    `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
    `${urls}\n` +
    `</urlset>\n`
  );
}

/**
 * English locale bundle used by page templates.
 *
 * @param job - Job providing the app name for copy.
 * @returns TypeScript module source.
 */
function i18nEnTs(job: Job): string {
  const pages = PAGES.map((name) => {
    const key = name.toLowerCase();
    return (
      `  ${key}: {\n` +
      `    title: '${name}',\n` +
      `    body: '${name} page for ${job.slug}.'\n` +
      `  }`
    );
  }).join(',\n');
  return (
    `/**\n` +
    ` * Central English locale bundle for all user-facing copy.\n` +
    ` * Components must reference these keys; no inline UI strings.\n` +
    ` */\n` +
    `export const en = {\n` +
    `  app: {\n` +
    `    name: '${job.slug}',\n` +
    `    primaryNav: 'Primary',\n` +
    `    footerCopyright: '© ${job.slug}'\n` +
    `  },\n` +
    `  pages: {\n${pages}\n  }\n` +
    `} as const;\n`
  );
}

/**
 * Page component that reads title and body from the locale bundle.
 *
 * @param name - Page name (Home, About, …).
 * @returns TypeScript React module source.
 */
function pageComponent(name: string): string {
  const key = name.toLowerCase();
  return (
    `import { Page } from '../components/Page';\n` +
    `import { en } from '../i18n/en';\n\n` +
    `/** ${name} page. Copy lives in the locale bundle (fe-i18n-central-copy). */\n` +
    `export function ${name}(): JSX.Element {\n` +
    `  const copy = en.pages.${key};\n` +
    `  return (\n` +
    `    <Page title={copy.title}>\n` +
    `      <p>{copy.body}</p>\n` +
    `    </Page>\n` +
    `  );\n` +
    `}\n`
  );
}

/**
 * Flat ESLint config mirroring the RedAnvil root standard for generated apps.
 *
 * @returns eslint.config.js source.
 */
function eslintConfigJs(): string {
  return (
    `import tseslint from '@typescript-eslint/eslint-plugin';\n` +
    `import tsparser from '@typescript-eslint/parser';\n\n` +
    `/** Flat ESLint config for the generated app (u-typing-no-any, u-conc-dead-code). */\n` +
    `export default [\n` +
    `  { ignores: ['**/dist/**', '**/node_modules/**', '**/*.config.*'] },\n` +
    `  {\n` +
    `    files: ['**/*.{ts,tsx}'],\n` +
    `    languageOptions: {\n` +
    `      parser: tsparser,\n` +
    `      parserOptions: { project: false, ecmaFeatures: { jsx: true } }\n` +
    `    },\n` +
    `    plugins: { '@typescript-eslint': tseslint },\n` +
    `    rules: {\n` +
    `      '@typescript-eslint/no-explicit-any': 'error',\n` +
    `      '@typescript-eslint/no-unused-vars': [\n` +
    `        'error',\n` +
    `        {\n` +
    `          argsIgnorePattern: '^_',\n` +
    `          varsIgnorePattern: '^_',\n` +
    `          caughtErrorsIgnorePattern: '^_'\n` +
    `        }\n` +
    `      ],\n` +
    `      'no-unreachable': 'error',\n` +
    `      'no-constant-condition': 'error',\n` +
    `      'no-dupe-else-if': 'error',\n` +
    `      'no-unsafe-negation': 'error',\n` +
    `      'no-console': 'off'\n` +
    `    }\n` +
    `  }\n` +
    `];\n`
  );
}

/**
 * Canonical route table shared by the router and covered by a behavioral test.
 *
 * @returns TypeScript module source.
 */
function routesTs(): string {
  return (
    `/** A single app route path and its page name. */\n` +
    `export interface AppRoute {\n` +
    `  /** URL path including leading slash (or \`/\` for home). */\n` +
    `  path: string;\n` +
    `  /** Page component export name. */\n` +
    `  name: string;\n` +
    `}\n\n` +
    `/** Canonical routes for the generated app shell. */\n` +
    `export const ROUTES: readonly AppRoute[] = [\n` +
    `  { path: '/', name: 'Home' },\n` +
    `  { path: '/about', name: 'About' },\n` +
    `  { path: '/terms', name: 'Terms' },\n` +
    `  { path: '/privacy', name: 'Privacy' },\n` +
    `  { path: '/contact', name: 'Contact' }\n` +
    `] as const;\n\n` +
    `/**\n` +
    ` * Look up the URL path for a page export name.\n` +
    ` *\n` +
    ` * @param name - Page component name (e.g. \`About\`).\n` +
    ` * @returns The route path, or undefined when the name is unknown.\n` +
    ` */\n` +
    `export function pathForPage(name: string): string | undefined {\n` +
    `  return ROUTES.find((route) => route.name === name)?.path;\n` +
    `}\n`
  );
}

/**
 * Behavioral test for the route table the scaffold emits.
 *
 * @returns Vitest module source.
 */
function routesTestTs(): string {
  return (
    `import { describe, it, expect } from 'vitest';\n` +
    `import { ROUTES, pathForPage } from './routes';\n\n` +
    `describe('ROUTES', () => {\n` +
    `  it('exposes the five required shell paths', () => {\n` +
    `    expect(ROUTES.map((r) => r.path)).toEqual([\n` +
    `      '/',\n` +
    `      '/about',\n` +
    `      '/terms',\n` +
    `      '/privacy',\n` +
    `      '/contact'\n` +
    `    ]);\n` +
    `  });\n\n` +
    `  it('maps page names to their paths', () => {\n` +
    `    expect(pathForPage('Home')).toBe('/');\n` +
    `    expect(pathForPage('About')).toBe('/about');\n` +
    `    expect(pathForPage('Contact')).toBe('/contact');\n` +
    `    expect(pathForPage('Missing')).toBeUndefined();\n` +
    `  });\n` +
    `});\n`
  );
}

/**
 * Build the generated app's source tree, keyed by repo-relative path.
 * Real, corpus-compliant seed files — not lorem or placeholders.
 *
 * @param job - Validated job (including optional entities for D1 DDL).
 * @returns Map of relative paths to file contents.
 */
export function appFiles(job: Job): Record<string, string> {
  const files: Record<string, string> = {
    'package.json':
      JSON.stringify(
        {
          name: job.slug,
          private: true,
          type: 'module',
          scripts: {
            dev: 'vite',
            build: 'tsc -b && vite build',
            preview: 'wrangler pages dev ./dist',
            typecheck: 'tsc -b',
            lint: 'eslint . --max-warnings 0',
            test: 'vitest run'
          },
          dependencies: {
            react: '^18.3.0',
            'react-dom': '^18.3.0',
            'react-router-dom': '^6.26.0'
          },
          devDependencies: {
            '@types/react': '^18.3.0',
            '@types/react-dom': '^18.3.0',
            '@typescript-eslint/eslint-plugin': '^8.0.0',
            '@typescript-eslint/parser': '^8.0.0',
            '@vitejs/plugin-react': '^4.3.0',
            eslint: '^9.0.0',
            tailwindcss: '^3.4.0',
            typescript: '^5.6.0',
            vite: '^5.4.0',
            vitest: '^2.0.0',
            wrangler: '^3.78.0'
          }
        },
        null,
        2
      ) + '\n',
    'tsconfig.json':
      JSON.stringify(
        {
          compilerOptions: {
            target: 'ES2022',
            lib: ['ES2022', 'DOM', 'DOM.Iterable'],
            module: 'ESNext',
            moduleResolution: 'Bundler',
            jsx: 'react-jsx',
            strict: true,
            noUncheckedIndexedAccess: true,
            noEmit: true,
            skipLibCheck: true,
            resolveJsonModule: true
          },
          include: ['src', 'functions']
        },
        null,
        2
      ) + '\n',
    '.gitignore': ['node_modules/', 'dist/', '.env', '.dev.vars', '.wrangler/'].join('\n') + '\n',
    'wrangler.toml':
      `name = "${job.slug}"\n` +
      `compatibility_date = "2026-07-01"\n` +
      `pages_build_output_dir = "dist"\n\n` +
      `[[d1_databases]]\n` +
      `binding = "DB"\n` +
      `database_name = "${job.slug}-db"\n` +
      `database_id = "REPLACE_WITH_D1_ID"\n`,
    'index.html':
      `<!doctype html>\n` +
      `<html lang="en">\n` +
      `  <head>\n` +
      `    <meta charset="UTF-8" />\n` +
      `    <meta name="viewport" content="width=device-width, initial-scale=1" />\n` +
      `    <title>${job.slug}</title>\n` +
      `    <meta name="description" content="${job.prompt.slice(0, 150)}" />\n` +
      `    <meta property="og:title" content="${job.slug}" />\n` +
      `    <meta property="og:type" content="website" />\n` +
      `    <meta property="og:image" content="/og.svg" />\n` +
      `  </head>\n` +
      `  <body>\n` +
      `    <div id="root"></div>\n` +
      `    <script type="module" src="/src/main.tsx"></script>\n` +
      `  </body>\n` +
      `</html>\n`,
    'public/robots.txt': 'User-agent: *\nAllow: /\n',
    'public/sitemap.xml': sitemapXml(job.slug),
    'public/og.svg': ogSvg(job.slug),
    'migrations/0001_init.sql': migrationSql(job),
    'eslint.config.js': eslintConfigJs(),
    'design-system/tokens.json': JSON.stringify(TOKENS_JSON, null, 2) + '\n',
    'src/main.tsx':
      `import { StrictMode } from 'react';\n` +
      `import { createRoot } from 'react-dom/client';\n` +
      `import { App } from './App';\n\n` +
      `createRoot(document.getElementById('root')!).render(\n` +
      `  <StrictMode>\n` +
      `    <App />\n` +
      `  </StrictMode>\n` +
      `);\n`,
    // `fe-light-dark` is a BLOCKER: light and dark, a visible toggle, a stated
    // default, AA in both. The scaffold used to ship one flat token object and
    // no stylesheet at all, so a generated app could not satisfy the rule from
    // its own starting point — the builder had to invent the entire theme
    // system before the gate could pass. It ships one now, dark by default.
    'src/theme.css': themeCss(),
    'src/theme.ts': themeTs(),
    'src/components/ThemeToggle.tsx': themeToggleTsx(),
    'src/i18n/en.ts': i18nEnTs(job),
    'src/lib/routes.ts': routesTs(),
    'src/lib/routes.test.ts': routesTestTs(),
    'src/components/Page.tsx':
      `import type { ReactNode } from 'react';\n` +
      `import { en } from '../i18n/en';\n\n` +
      `export interface PageProps {\n` +
      `  /** Page title, rendered as the single h1. */\n` +
      `  title: string;\n` +
      `  /** Page body. */\n` +
      `  children: ReactNode;\n` +
      `}\n\n` +
      `/** Shared page shell: sticky header, one h1, professional footer. */\n` +
      `export function Page({ title, children }: PageProps): JSX.Element {\n` +
      `  return (\n` +
      `    <div>\n` +
      `      <header style={{ position: 'sticky', top: 0 }}>\n` +
      `        <nav aria-label={en.app.primaryNav}>{en.app.name}</nav>\n` +
      `      </header>\n` +
      `      <main>\n` +
      `        <h1>{title}</h1>\n` +
      `        {children}\n` +
      `      </main>\n` +
      `      <footer>\n` +
      `        <small>{en.app.footerCopyright}</small>\n` +
      `      </footer>\n` +
      `    </div>\n` +
      `  );\n` +
      `}\n`,
    'functions/api/health.ts':
      `/** Health endpoint — proves the Worker runtime boots (lg-runtime-parity). */\n` +
      `export function onRequest(context: { request: Request }): Response {\n` +
      `  const origin = new URL(context.request.url).origin;\n` +
      `  return new Response(JSON.stringify({ status: 'ok' }), {\n` +
      `    headers: {\n` +
      `      'content-type': 'application/json',\n` +
      `      'x-content-type-options': 'nosniff',\n` +
      `      'referrer-policy': 'same-origin',\n` +
      `      'access-control-allow-origin': origin,\n` +
      `      'access-control-allow-methods': 'GET'\n` +
      `    }\n` +
      `  });\n` +
      `}\n`,
    'functions/lib/auth.ts':
      `/** Web Crypto auth: PBKDF2 password hashing, HMAC-SHA256 tokens. Runs natively on Workers. */\n` +
      `export async function hashPassword(password: string, salt: BufferSource): Promise<ArrayBuffer> {\n` +
      `  const key = await crypto.subtle.importKey('raw', new TextEncoder().encode(password), 'PBKDF2', false, [\n` +
      `    'deriveBits'\n` +
      `  ]);\n` +
      `  return crypto.subtle.deriveBits({ name: 'PBKDF2', salt, iterations: 100_000, hash: 'SHA-256' }, key, 256);\n` +
      `}\n`
  };

  const routeImports = PAGES.map((p) => `import { ${p} } from './pages/${p}';`).join('\n');
  const routeElements = PAGES.map((p) => {
    const pathExpr =
      p === 'Home' ? `pathForPage('Home') ?? '/'` : `pathForPage('${p}') ?? '/${p.toLowerCase()}'`;
    return `        <Route path={${pathExpr}} element={<${p} />} />`;
  }).join('\n');
  files['src/App.tsx'] =
    `import { BrowserRouter, Routes, Route } from 'react-router-dom';\n` +
    `import { pathForPage } from './lib/routes';\n` +
    `${routeImports}\n\n` +
    `/** App router: composes the required pages from the shared route table. */\n` +
    `export function App(): JSX.Element {\n` +
    `  return (\n` +
    `    <BrowserRouter>\n` +
    `      <Routes>\n` +
    `${routeElements}\n` +
    `      </Routes>\n` +
    `    </BrowserRouter>\n` +
    `  );\n` +
    `}\n`;

  for (const p of PAGES) files[`src/pages/${p}.tsx`] = pageComponent(p);
  return files;
}

/**
 * Light and dark CSS variables, dark by default.
 *
 * Raw hex is correct here and nowhere else — this file IS the token definition,
 * which is why `fe-theme-tokens-only` exempts `theme.css`.
 *
 * Dark is the default deliberately, and the choice is STATED rather than
 * inherited from `prefers-color-scheme`: a product designed dark-first should
 * open dark, or most visitors never see the design it was built as. A saved
 * choice always wins, so this sets the starting point, not the user's control.
 *
 * @returns Contents of `src/theme.css`.
 */
function themeCss(): string {
  return [
    '/* Theme variables. Dark is the default; light is opt-in via data-theme. */',
    ':root {',
    '  --bg: #0b0b0f;',
    '  --surface: #15151d;',
    '  --surface-elevated: #1c1c26;',
    '  --text: #f5f5f7;',
    '  --text-on-accent: #ffffff;',
    '  --muted: #9b9ba6;',
    '  --accent: #e5484d;',
    '  --border: #2b2b36;',
    '}',
    '',
    ":root[data-theme='light'] {",
    '  --bg: #f4f4f6;',
    '  --surface: #ffffff;',
    '  --surface-elevated: #ffffff;',
    '  --text: #111114;',
    '  --text-on-accent: #ffffff;',
    '  --muted: #5c5c68;',
    '  --accent: #c62828;',
    '  --border: #d8d8e0;',
    '}',
    '',
    'html {',
    '  background: var(--bg);',
    '  color: var(--text);',
    '}',
    '',
    'body {',
    '  margin: 0;',
    '  font-family:',
    '    system-ui,',
    '    -apple-system,',
    '    Segoe UI,',
    '    sans-serif;',
    '  /* 16px floor: fe-type-floor is a blocker. */',
    '  font-size: 16px;',
    '  line-height: 1.5;',
    '}',
    ''
  ].join('\n');
}

/**
 * Theme accessor. Values are CSS variables so a theme swap needs no re-render.
 *
 * @returns Contents of `src/theme.ts`.
 */
function themeTs(): string {
  return [
    "import tokens from '../design-system/tokens.json';",
    '',
    '/**',
    ' * Styling truth for the app (fe-theme-tokens-only).',
    ' *',
    ' * Colours resolve through CSS variables defined in `theme.css`, so switching',
    ' * theme is a single attribute on <html> rather than a React re-render. Space,',
    ' * radius and type come straight from the shared token file.',
    ' */',
    'export const theme = {',
    '  color: {',
    "    bg: 'var(--bg)',",
    "    surface: 'var(--surface)',",
    "    surfaceElevated: 'var(--surface-elevated)',",
    "    text: 'var(--text)',",
    "    textOnAccent: 'var(--text-on-accent)',",
    "    muted: 'var(--muted)',",
    "    accent: 'var(--accent)',",
    "    border: 'var(--border)'",
    '  },',
    '  space: tokens.space,',
    '  radius: tokens.radius,',
    '  type: tokens.type',
    '} as const;',
    ''
  ].join('\n');
}

/**
 * Theme toggle: flips `data-theme`, persists the choice, states the default.
 *
 * @returns Contents of `src/components/ThemeToggle.tsx`.
 */
function themeToggleTsx(): string {
  return [
    "import { useCallback, useEffect, useState } from 'react';",
    "import { theme } from '../theme';",
    '',
    "type ThemeChoice = 'light' | 'dark';",
    '',
    '/**',
    " * The user's saved choice, else the brand default.",
    ' *',
    ' * Dark is the stated default. A saved choice always wins.',
    ' *',
    ' * @param stored - Raw localStorage value, or null.',
    ' * @returns The theme to apply.',
    ' */',
    'function resolveTheme(stored: string | null): ThemeChoice {',
    "  return stored === 'light' || stored === 'dark' ? stored : 'dark';",
    '}',
    '',
    '/**',
    ' * Header control that switches between light and dark.',
    ' *',
    ' * @returns The toggle button.',
    ' */',
    'export function ThemeToggle(): JSX.Element {',
    "  const [mode, setMode] = useState<ThemeChoice>('dark');",
    '',
    '  useEffect(() => {',
    "    const next = resolveTheme(localStorage.getItem('theme'));",
    '    setMode(next);',
    '    document.documentElement.dataset.theme = next;',
    '  }, []);',
    '',
    '  const toggle = useCallback((): void => {',
    '    setMode((current): ThemeChoice => {',
    "      const next: ThemeChoice = current === 'dark' ? 'light' : 'dark';",
    '      document.documentElement.dataset.theme = next;',
    "      localStorage.setItem('theme', next);",
    '      return next;',
    '    });',
    '  }, []);',
    '',
    '  return (',
    '    <button',
    '      type="button"',
    '      onClick={toggle}',
    "      aria-label={mode === 'dark' ? 'Switch to light theme' : 'Switch to dark theme'}",
    '      style={{',
    '        minWidth: 44,',
    '        minHeight: 44,',
    '        borderRadius: theme.radius.md,',
    '        border: `1px solid ${theme.color.border}`,',
    '        background: theme.color.surface,',
    '        color: theme.color.text,',
    '        fontSize: theme.type.scale[2],',
    "        cursor: 'pointer'",
    '      }}',
    '    >',
    "      <span aria-hidden=\"true\">{mode === 'dark' ? '☀' : '☾'}</span>",
    '    </button>',
    '  );',
    '}',
    ''
  ].join('\n');
}
