/**
 * The RedAnvil process map as data, with a fail-closed artifact contract per step.
 *
 * This file is the single source of truth. The n8n workflow is GENERATED from it
 * (build-workflow.mjs) rather than written alongside it, because a hand-authored
 * workflow can silently omit a step -- which is exactly how the logo role was
 * skipped for pet-sitter while the gate still reported 100/100.
 *
 * Two ideas do the work:
 *
 * 1. `requires` gives a step's artifact contract. A step is not done because it
 *    ran; it is done when the named artifacts exist, carry substance, and satisfy
 *    their assertions. Unrecorded means FAILED, never "probably fine".
 *
 * 2. `dependsOn` orders the map. A build step cannot start until the design steps
 *    it depends on are DONE by that contract. A gate cannot ask for what was never
 *    started, so ordering is enforced at the start of the process, not scored at
 *    the end of it.
 */

/**
 * @typedef {object} ArtifactContract
 * @property {string} path file or directory, relative to the app directory
 * @property {'file'|'dir'} kind what is expected at that path
 * @property {number} [minBytes] substance floor for a file
 * @property {number} [minCount] minimum matching entries for a directory
 * @property {string} [glob] extension filter for a directory count, e.g. '.png'
 * @property {string[]} [mustContain] substrings that must appear in a text file
 * @property {string[]} [mustNotContain] substrings that disqualify it (placeholders)
 * @property {string} why the failure this contract exists to prevent
 */

/**
 * @typedef {object} ProcessStep
 * @property {string} id
 * @property {string} role
 * @property {string} summary
 * @property {string[]} dependsOn
 * @property {boolean} humanGate whether a person must decide before the next step
 * @property {boolean} skippable always false today; present so a skip is explicit
 * @property {ArtifactContract[]} requires
 * @property {string} [reworkTo] step this routes BACK to on failure. The map was
 *   a straight line while the real process is loop-heavy: a blank DECISION.md
 *   loops to the pick, a failed gate routes to assign, and assign routes through
 *   the debugger back into build. A linear map cannot express "try again".
 * @property {number} [maxCycles] how many times this loop may run before the
 *   build is abandoned. An unbounded rework loop is how a build runs forever
 *   without anyone deciding to stop.
 * @property {'script'|'agent'|'human'} [kind] how the role executes. `agent`
 *   roles are genuinely judgement work and belong in an n8n AI Agent node;
 *   `script` roles are deterministic and belong in Execute Command.
 */

/**
 * Markers whose presence means a document still holds unfilled content.
 *
 * Matched as whole words, and deliberately NOT including the bare word
 * "placeholder": the product brief contains the line "Real brand mark, not emoji
 * or letter placeholders", which is a document PROHIBITING placeholders. A naive
 * substring check failed it and blocked the entire process map behind a false
 * failure. A check that fires on a document for forbidding the thing it looks
 * for is worse than no check.
 */
export const PLACEHOLDER_MARKERS = ['TBD', 'TODO', 'Lorem ipsum', 'Sample profile used by'];

/** @type {ProcessStep[]} */
export const PROCESS = [
  {
    id: 'prd',
    role: 'prd',
    summary: 'Generate the PRD by driving the RedAnvil app-builder, not by hand-writing one',
    dependsOn: [],
    humanGate: false,
    skippable: false,
    requires: [
      {
        // The owner's standing instruction: every app starts from a PRD produced
        // by https://redanvil.pages.dev/. Note that /api/prd and /api/generate
        // are SPA fallback, not endpoints -- they return the same HTML as a
        // nonsense path, and only /api/health answers JSON. So this step DRIVES
        // the wizard with Playwright and captures what it produces. A
        // hand-written PRD defeats the point: the app-builder is the product,
        // and using it on every new app is the only real dogfooding.
        path: 'docs/PRD.md',
        kind: 'file',
        minBytes: 2000,
        mustContain: ['Design direction'],
        mustNotContain: PLACEHOLDER_MARKERS,
        why: 'a PRD written by the orchestrator is its own opinion; one generated by the app-builder is the product being used on itself, and §7.3a Design direction is what stops every app looking the same'
      },
      {
        path: 'docs/prd-provenance.json',
        kind: 'file',
        minBytes: 120,
        mustContain: ['redanvil.pages.dev'],
        why: 'records that the PRD came from the deployed app-builder and which build produced it -- otherwise a hand-written file is indistinguishable from a generated one'
      }
    ]
  },
  {
    id: 'product',
    role: 'product',
    summary: 'Product brief: who it is for, the job, the one flow that must work',
    dependsOn: ['prd'],
    humanGate: false,
    skippable: false,
    requires: [
      {
        // Path read from the repo, not invented. The first draft of this file
        // guessed `docs/product/BRIEF.md`, which never existed, and the checker
        // blocked the whole map on a false failure -- the same class of mistake
        // as referencing a CSS class nobody defined.
        path: 'docs/PRODUCT-BRIEF.md',
        kind: 'file',
        minBytes: 1200,
        mustNotContain: PLACEHOLDER_MARKERS,
        why: 'a build with no product brief optimises the rubric instead of the user'
      }
    ]
  },
  {
    id: 'brainstorm',
    role: 'brainstorm',
    summary: 'Ranked features with a data-source note; unsourceable features flagged blocked',
    dependsOn: ['product'],
    humanGate: false,
    skippable: false,
    kind: 'agent',
    requires: [
      {
        path: 'docs/FEATURES.md',
        kind: 'file',
        minBytes: 800,
        mustContain: ['data source'],
        mustNotContain: PLACEHOLDER_MARKERS,
        why: 'a feature with no sourceable data is listed as blocked rather than built -- otherwise it ships as an empty screen'
      }
    ]
  },
  {
    id: 'inspo',
    role: 'design-inspo',
    summary: 'Reference intake from Mobbin and shipping apps, with sources recorded',
    dependsOn: ['product'],
    humanGate: false,
    skippable: false,
    kind: 'script',
    requires: [
      {
        // Scraping galleries is allowed as of 2026-08-06 at the owner's
        // instruction; what is not allowed is redistributing the screenshots.
        // They stay local and gitignored, and SOURCES.md is the committed record.
        path: 'design-refs/SOURCES.md',
        kind: 'file',
        minBytes: 600,
        mustContain: ['http'],
        why: 'a rule pack alone produces the same app every time; direction has to come from real shipping products, cited'
      }
    ]
  },
  {
    id: 'reuse',
    role: 'reuse-scout',
    summary: 'Search GitHub for existing implementations BEFORE writing any feature from scratch',
    dependsOn: ['product'],
    humanGate: false,
    skippable: false,
    requires: [
      {
        // Base rule 3 says use what exists before writing anything, and it was
        // enforced by memory, which means not enforced. pet-sitter hand-rolled
        // its way to a browsable directory with no booking flow while mature
        // open-source marketplace, availability-calendar and auth
        // implementations existed unexamined. The owner asked why this was not
        // enforced; the honest answer is that no step required it.
        path: 'docs/REUSE-SCAN.md',
        kind: 'file',
        minBytes: 800,
        mustContain: ['github.com', 'licence', 'verdict'],
        mustNotContain: PLACEHOLDER_MARKERS,
        why: 'a feature written from scratch when a maintained implementation exists is a cost the owner pays twice -- once to build it and again to fix it'
      }
    ]
  },
  {
    id: 'logo',
    role: 'logo',
    summary: 'Five real generated brand marks, a gallery, and an OPEN decision',
    dependsOn: ['product'],
    humanGate: true,
    skippable: false,
    requires: [
      {
        // Deliberately NOT a count of candidate PNGs. Committing marks under
        // design-refs violates hyg-no-binaries, which allows binaries only under
        // public/assets/static/images/screenshots -- and that rule is right.
        // Candidate images are working files; what has to survive is the
        // decision text and the mark that actually ships.
        path: 'public/brand-mark.png',
        kind: 'file',
        minBytes: 2000,
        why: 'pet-sitter shipped a single copied mark because this step never ran; the chosen mark must reach public/, not just an archive'
      },
      {
        path: 'design-refs/logos/gallery.html',
        kind: 'file',
        minBytes: 800,
        why: 'without a gallery the owner cannot pick, so the step produces no decision'
      },
      {
        path: 'design-refs/logos/DECISION.md',
        kind: 'file',
        minBytes: 300,
        mustContain: ['mark-05'],
        mustNotContain: PLACEHOLDER_MARKERS,
        why: 'a blank DECISION.md is MISSING, and it must list all five candidates -- naming mark-05 proves five were explored, which a single copied mark cannot fake'
      }
    ]
  },
  {
    id: 'palette',
    role: 'palette',
    summary: 'Five distinct colour + type directions, each shown light AND dark, OPEN decision',
    dependsOn: ['product'],
    humanGate: true,
    skippable: false,
    requires: [
      {
        path: 'design-refs/palettes/gallery.html',
        kind: 'file',
        minBytes: 2000,
        why: 'palette was never a separate choice axis, so the owner was never offered one -- the base colour shipped because I picked it, not because it was chosen'
      },
      {
        path: 'design-refs/palettes/DECISION.md',
        kind: 'file',
        minBytes: 400,
        mustContain: ['palette-05', 'dark'],
        mustNotContain: PLACEHOLDER_MARKERS,
        why: 'naming palette-05 proves five directions were explored; requiring "dark" proves each was judged in both themes rather than light-only'
      }
    ]
  },
  {
    id: 'layout',
    role: 'layout',
    summary: 'Three structurally distinct layout options, gallery, OPEN decision',
    dependsOn: ['product'],
    humanGate: true,
    skippable: false,
    requires: [
      {
        path: 'design-refs/design-options',
        kind: 'dir',
        glob: '.html',
        minCount: 4,
        why: 'three options plus a gallery; fewer means the exploration did not happen'
      },
      {
        path: 'design-refs/design-options/DECISION.md',
        kind: 'file',
        minBytes: 600,
        mustContain: ['Forbidden'],
        mustNotContain: PLACEHOLDER_MARKERS,
        why: 'R38 -- a decision that keeps several designs must name the flattened outcome as forbidden, or the build will faithfully homogenise them'
      }
    ]
  },
  {
    id: 'decide',
    reworkTo: 'layout',
    maxCycles: 5,
    role: 'user-picks',
    summary: 'The owner picks a logo, a palette and a layout. Nothing builds before this',
    dependsOn: ['logo', 'layout', 'palette'],
    humanGate: true,
    skippable: false,
    requires: [
      {
        path: 'design-refs/design-options/DECISION.md',
        kind: 'file',
        minBytes: 600,
        mustContain: ['DECIDED'],
        why: 'the build must read a recorded choice, never infer one'
      },
      {
        path: 'design-refs/logos/DECISION.md',
        kind: 'file',
        minBytes: 300,
        mustContain: ['CHOSEN'],
        why: 'the chosen mark must be named in writing, or a later worktree ships whatever it finds'
      },
      {
        // Added after the owner asked why no colour or theme options were ever
        // offered. There was no palette step, so nothing required one and the
        // base colour shipped because I chose it. The choice axis has to exist
        // in the map before it can be enforced anywhere.
        path: 'design-refs/palettes/DECISION.md',
        kind: 'file',
        minBytes: 400,
        mustContain: ['CHOSEN'],
        why: 'the palette must be a recorded owner choice, never a default carried over from whichever layout option happened to win'
      }
    ]
  },
  {
    id: 'integration',
    role: 'integration',
    summary: 'Wire the real external data source and PROVE it answers today',
    dependsOn: ['reuse'],
    humanGate: false,
    skippable: false,
    kind: 'script',
    reworkTo: 'build',
    maxCycles: 3,
    requires: [
      {
        // The owner asked why the app had no real location data. The answer was
        // structural: R33 says "prove the integration exists TODAY" but no STEP
        // required one, so nothing could demand it -- the same hole that let the
        // logo and palette roles be skipped. An app whose domain is discovery
        // and whose only data is six seeded rows is a demo, not a product.
        path: 'evidence/integration-proof.json',
        kind: 'file',
        minBytes: 200,
        mustContain: ['provider', '"live": true'],
        why: 'a documented API is not a working one; the proof records a real response captured from the live provider, with the key server-side'
      }
    ]
  },
  {
    id: 'testwriter',
    kind: 'agent',
    role: 'testwriter',
    summary: 'Acceptance tests written from the PRD BEFORE any build',
    dependsOn: ['decide'],
    humanGate: false,
    skippable: false,
    requires: [
      {
        // The diagram is explicit: "acceptance tests from the PRD BEFORE any
        // build". Tests written after the build describe what was built, not
        // what was asked for, which is how a green suite coexists with a missing
        // feature -- pet-sitter passed its suite with no booking flow at all.
        path: 'test/acceptance',
        kind: 'dir',
        glob: '.ts',
        minCount: 1,
        why: 'tests written after the build assert the implementation instead of the requirement'
      },
      {
        // Integration layer, in pytest. Acceptance tests above run in vitest and
        // mostly exercise the app in isolation; this one has to prove the parts
        // work TOGETHER -- real D1 reads and writes, the Pages Functions
        // endpoints, and a real browser against a served build.
        //
        // It is a separate requirement rather than prose in the role prompt
        // because a requirement that lives only in a prompt is not enforced by
        // anything: the role can skip it and still be counted as having run.
        // Declared here, an absent integration suite fails the contract.
        path: 'test/integration',
        kind: 'dir',
        glob: '.py',
        minCount: 1,
        why: 'a suite that mocks every collaborator passes while the seams between them are broken'
      }
    ]
  },
  {
    id: 'build',
    role: 'engineer',
    summary: 'Implement the decided design',
    dependsOn: ['testwriter', 'integration'],
    humanGate: false,
    skippable: false,
    requires: [
      {
        path: 'src',
        kind: 'dir',
        glob: '.tsx',
        minCount: 3,
        why: 'a build step that changed no source did not build'
      }
    ]
  },
  {
    id: 'content',
    role: 'content',
    summary: 'Legal pages with real substance, empty states, coverage boundaries',
    dependsOn: ['build'],
    humanGate: false,
    skippable: false,
    requires: [
      {
        path: 'src/pages/Terms.tsx',
        kind: 'file',
        minBytes: 1500,
        mustNotContain: PLACEHOLDER_MARKERS,
        why: 'legal pages specced as "real content, no boilerplate" once shipped at 81 words'
      },
      {
        path: 'src/pages/Privacy.tsx',
        kind: 'file',
        minBytes: 1500,
        mustNotContain: PLACEHOLDER_MARKERS,
        why: 'same failure; substance is measured in bytes, not promised in a spec'
      }
    ]
  },
  {
    id: 'runners',
    role: 'u-test-runners',
    summary: 'Every test lane run independently: vitest unit, browser, vrt, pytest',
    dependsOn: ['content'],
    humanGate: false,
    skippable: false,
    requires: [
      {
        path: 'evidence/test-lanes.json',
        kind: 'file',
        minBytes: 200,
        // The old contract wanted the STRINGS 'vitest' and 'exitCode' to appear.
        // A file recording `typecheck exitCode: 2` -- a FAILING lane -- satisfied
        // it, because the words were present. It also passed an app with 8 tests
        // total, an unwired acceptance lane, and no pytest at all.
        //
        // Now every lane must record success, the acceptance and pytest lanes
        // must be present, and a minimum test count must be met. A suite that
        // exists is not a suite that covers anything.
        mustContain: ['"allLanesPassed": true', '"acceptance"', '"pytest"', '"enoughTests": true'],
        mustNotContain: ['"exitCode": 1', '"exitCode": 2'],
        why: 'a lane that was never run is not a lane that passed, and a recorded failure must never satisfy the step that records it'
      }
    ]
  },
  {
    id: 'visual',
    reworkTo: 'build',
    maxCycles: 3,
    role: 'qa-visual',
    summary: 'Render every surface at 375/768/1280 in both themes and OPEN the images',
    dependsOn: ['build'],
    humanGate: false,
    skippable: false,
    requires: [
      {
        // The renders themselves are gitignored -- 40 PNGs per rebuild is real
        // repo bloat. But evidence that cannot travel is not evidence: a fresh
        // checkout could never verify this step. So the manifest is the
        // committed artifact, and it must carry a content hash per render.
        //
        // A list of filenames would be the "artifact exists != work was done"
        // trap one level up -- anyone can write twelve names. Twelve DISTINCT
        // sha256 values cannot be produced without twelve distinct images.
        path: 'design-refs/design-options/renders/MANIFEST.json',
        kind: 'file',
        minBytes: 400,
        jsonDistinctHashes: 12,
        why: 'R36 -- the claimed matrix was 24 renders and 10 existed; count the artifacts against the claim'
      }
    ]
  },
  {
    id: 'ui-live',
    role: 'qa-live-ui',
    summary: 'Drive the DEPLOYED UI and prove it calls the live endpoints and paints a big-enough mark',
    dependsOn: ['visual'],
    humanGate: false,
    skippable: false,
    kind: 'script',
    reworkTo: 'build',
    maxCycles: 3,
    requires: [
      {
        // THREE times now an endpoint existed and the UI never called it:
        // pet-sitter's assistant button, sushi-finder's Places search, and
        // sushi-finder's assistant. Every one passed source review, unit tests,
        // and an endpoint probe, because each of those inspects one side of a
        // wire that was never connected.
        //
        // The only thing that catches it is driving the deployed page and
        // recording which requests it actually makes. This contract requires
        // that recording, and requires every live endpoint to appear in it.
        path: 'evidence/ui-live-calls.json',
        kind: 'file',
        minBytes: 200,
        mustContain: ['"allLiveEndpointsCalled": true', '"brandMarkOk": true'],
        why: 'an endpoint test and a UI test both pass while the wire between them is missing; and a brand mark rule enforced only by the gate is not enforced during a build'
      }
    ]
  },
  {
    id: 'qa-runtime',
    reworkTo: 'build',
    maxCycles: 3,
    role: 'qa-runtime',
    summary: 'Deployed routes and bindings answer for real',
    dependsOn: ['visual'],
    humanGate: false,
    skippable: false,
    requires: [
      {
        path: 'evidence/api-live.json',
        kind: 'file',
        minBytes: 120,
        why: 'a 200 on the homepage only proves static assets served; every route and binding is probed separately'
      }
    ]
  },
  {
    id: 'judge',
    kind: 'agent',
    reworkTo: 'build',
    maxCycles: 3,
    role: 'independent-judge',
    summary: 'Fresh context reviews the diff and may dissent',
    dependsOn: ['qa-runtime'],
    humanGate: false,
    skippable: false,
    requires: [
      {
        path: 'evidence/judge-diff.json',
        kind: 'file',
        minBytes: 200,
        why: 'a judge reviewing its own author never dissents -- 258 verdicts with 0 fails, against 6 of 10 from a fresh reviewer'
      }
    ]
  },
  {
    id: 'qa-data',
    role: 'qa-data',
    summary: 'Every citation and link resolves',
    dependsOn: ['qa-runtime'],
    humanGate: false,
    skippable: false,
    kind: 'script',
    reworkTo: 'build',
    maxCycles: 3,
    requires: [
      {
        path: 'evidence/link-check.json',
        kind: 'file',
        minBytes: 100,
        // "checked" alone passed a run that FOUND a dead link. The role reported
        // it, exited 1, and the contract shrugged because the word was present.
        // Requiring zero dead links is the difference between running a check
        // and honouring it.
        mustContain: ['"dead": 0'],
        why: 'a dead citation is indistinguishable from a fabricated one to a reader, so finding one must fail the step'
      }
    ]
  },
  {
    id: 'user-refuse',
    role: 'user-refuse',
    summary: 'Adversarial acceptance: sees only the URL, default answer is no',
    dependsOn: ['qa-data'],
    humanGate: false,
    skippable: false,
    kind: 'agent',
    reworkTo: 'pm',
    maxCycles: 3,
    requires: [
      {
        path: 'evidence/user-refuse.json',
        kind: 'file',
        minBytes: 120,
        mustContain: ['verdict'],
        why: 'a reviewer who starts from yes finds nothing; this one starts from no and must be argued out of it'
      }
    ]
  },
  {
    id: 'pm',
    role: 'pm',
    summary: 'Assign every unmet row to its owning role; an unowned row is a hard error',
    dependsOn: ['user-refuse'],
    humanGate: false,
    skippable: false,
    kind: 'agent',
    requires: [
      {
        path: 'evidence/assignments.json',
        kind: 'file',
        minBytes: 80,
        mustContain: ['unmet'],
        why: 'an unmet row with no owning role is how a finding is discovered and then quietly dropped'
      }
    ]
  },
  {
    id: 'debugger',
    role: 'debugger',
    summary: 'Root cause established BEFORE any fix is written',
    dependsOn: ['pm'],
    humanGate: false,
    skippable: false,
    kind: 'agent',
    reworkTo: 'build',
    maxCycles: 3,
    requires: [
      {
        path: 'evidence/root-cause.md',
        kind: 'file',
        minBytes: 300,
        mustContain: ['root cause'],
        mustNotContain: PLACEHOLDER_MARKERS,
        why: 'a fix written before the cause is known treats the symptom, and the defect returns under a different name'
      }
    ]
  },
  {
    id: 'reverify',
    reworkTo: 'build',
    maxCycles: 3,
    role: 'reverify',
    summary: 'Re-measure against the deployed HEAD build and re-stamp verdicts',
    dependsOn: ['debugger'],
    humanGate: false,
    skippable: false,
    requires: [
      {
        // The push was refused for exactly this: "evidence is stale relative to
        // the commit it claims to review". Every change to src/ invalidates the
        // recorded verdicts, so a recorded review is evidence only for the
        // commit it was taken at. Leaving that to a human to remember is what
        // produced the refusal; here the process cannot reach `ship` without it.
        //
        // `dirty` matters as much as `commit`: measuring a dirty tree produces a
        // green result that describes no commit at all, which is worse than red.
        path: 'results/RESULTS.json',
        kind: 'file',
        minBytes: 200,
        provenanceMatchesHead: true,
        why: 'a verdict recorded at another commit, or against a dirty tree, is not evidence for this one'
      }
    ]
  },
  {
    id: 'ship',
    role: 'ship',
    summary: 'Deploy and prove the served asset hash matches the build',
    dependsOn: ['reverify'],
    humanGate: false,
    skippable: false,
    requires: [
      {
        path: '.redanvil/claims.json',
        kind: 'file',
        minBytes: 80,
        // "deployUrl" alone was satisfied by a FAILED deploy: ship wrote a claim
        // recording servedAsset null and assetHashMatches false, and the contract
        // passed because the string was present. Requiring the literal
        // "assetHashMatches": true is the difference between a claim and proof.
        mustContain: ['deployUrl', '"assetHashMatches": true'],
        why: 'a wrangler success message is not proof, and neither is a recorded URL; only a served asset hash matching the local build is'
      }
    ]
  }
];

/**
 * Steps in dependency order, failing loudly on an unknown or cyclic dependency.
 * @returns {ProcessStep[]} topologically sorted steps
 */
export function orderedSteps() {
  /** @type {ProcessStep[]} */
  const out = [];
  const byId = new Map(PROCESS.map((s) => [s.id, s]));
  /** @type {Set<string>} */
  const done = new Set();
  /** @type {Set<string>} */
  const visiting = new Set();

  /** @param {string} id */
  const visit = (id) => {
    if (done.has(id)) return;
    if (visiting.has(id)) throw new Error(`cyclic dependency at ${id}`);
    const step = byId.get(id);
    if (!step) throw new Error(`unknown dependency ${id}`);
    visiting.add(id);
    for (const dep of step.dependsOn) visit(dep);
    visiting.delete(id);
    done.add(id);
    out.push(step);
  };

  for (const s of PROCESS) visit(s.id);
  return out;
}
