-- Initial D1 schema for pet-sitter.
-- Generated by RedAnvil scaffold; apply with wrangler d1 migrations apply.

CREATE TABLE IF NOT EXISTS sitter (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT,
  neighbourhood TEXT,
  rate_per_night INTEGER,
  pet_types TEXT,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS pet (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT,
  species TEXT,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS booking (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  start_date TEXT,
  end_date TEXT,
  status TEXT,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS review (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  rating INTEGER,
  body TEXT,
  created_at TEXT NOT NULL
);
