import type { WizardAnswers } from './job';
import { slugFromPrompt } from './job';

/** The effort estimate shape consumed by the PRD (structurally matches estimate()). */
export interface TokenEstimate {
  iterations: number;
  tokens: number;
  confidence: string;
}

export interface Prd {
  slug: string;
  title: string;
  /** Original user prompt used to generate this PRD. */
  prompt: string;
  /** Complete PRD as GitHub-flavored markdown, ready to paste into Claude. */
  markdown: string;
}

const STOPWORDS = new Set([
  'a',
  'an',
  'the',
  'for',
  'with',
  'app',
  'application',
  'to',
  'of',
  'and'
]);

/** Derive a human product title from the prompt (Title Case, stopwords kept lowercase mid-title). */
function titleFromPrompt(prompt: string): string {
  const words = prompt
    .trim()
    .replace(/[^a-zA-Z0-9 ]+/g, ' ')
    .split(/\s+/)
    .filter(Boolean)
    .slice(0, 6);
  if (words.length === 0) return 'New App';
  return words
    .map((w, i) =>
      i > 0 && STOPWORDS.has(w.toLowerCase()) ? w.toLowerCase() : w[0]!.toUpperCase() + w.slice(1)
    )
    .join(' ');
}

/** Split the free-text entities field into a clean list. */
function entityList(entities: string): string[] {
  return entities
    .split(/[,;\n]+/)
    .map((e) => e.trim())
    .filter((e) => e.length > 0);
}

/**
 * Generates a complete, Claude-ready PRD (markdown) from the wizard answers and
 * the token estimate. Deterministic — the same answers always produce the same
 * document. Sections cover overview, users, features with acceptance criteria,
 * data model, enforced tech stack and design rules, test design, the effort
 * estimate, a scaffolding manifest, and a ready-to-paste initial build prompt.
 */
export function generatePrd(answers: WizardAnswers, cost: TokenEstimate): Prd {
  const prompt = answers.prompt.trim();
  const slug = slugFromPrompt(prompt);
  const title = titleFromPrompt(prompt);
  const entities = entityList(answers.entities);
  const appType = answers.appType.trim() || 'web application';
  const auth = answers.hasAuth;

  const entityRows =
    entities.length > 0
      ? entities
          .map((e) => `| ${e} | id, created_at, plus fields specific to ${e.toLowerCase()} |`)
          .join('\n')
      : '| Item | id, created_at, title, description |';

  const featureLines = [
    `- **Browse & search** — users can search and filter ${entities[0]?.toLowerCase() ?? 'items'}. *Acceptance:* a query returns matching results within 500ms and an empty query shows a helpful empty state.`,
    `- **Detail view** — clicking a result opens a full detail page. *Acceptance:* every list item routes to a detail page that renders its full record and a back link.`,
    auth
      ? `- **Accounts** — register and sign in with Web Crypto (PBKDF2 + HMAC-SHA256). *Acceptance:* a user can register, sign out, sign back in, and only see their own data.`
      : `- **Public access** — no login required. *Acceptance:* every page is reachable without authentication.`,
    ...entities
      .slice(0, 3)
      .map(
        (e) =>
          `- **Manage ${e}** — create, edit, and delete ${e.toLowerCase()} with confirmation before delete. *Acceptance:* CRUD works end-to-end and delete shows a confirm dialog.`
      )
  ].join('\n');

  const markdown = `# Product Requirements Document — ${title}

> Generated by RedAnvil App Builder. Paste this whole document into Claude (or Grok) to build the app. Threshold to ship: **score >= 90** on the RedAnvil rubric.

## 1. Summary

${prompt}

A ${appType} built as a full-stack app on Cloudflare. Target quality gate: 90/100.

## 2. Goals

- Deliver the core value in the summary above with the smallest correct implementation.
- Ship a clean, modern, mobile-first UI that passes a real visual review.
- Meet every rule in the enforced stack below; nothing merges below score 90.

## 3. Target users

People who need to ${prompt.replace(/^build (a|an|the)?\s*/i, '').replace(/^an?\s+app\s+(for|to)\s+/i, '') || 'use this app'}.

## 4. Core features

${featureLines}

## 5. Data model (Cloudflare D1)

| Table | Columns |
|-------|---------|
${entityRows}
${auth ? '| users | id, email (unique), password_hash, salt, created_at |\n| sessions | id, user_id, token_hash, expires_at |' : ''}

All queries are parameterized. Validate every input with Zod at the boundary.

## 6. Enforced tech stack (non-negotiable)

- Frontend: Vite + React + TypeScript (strict) + Tailwind CSS + React Router.
- Backend: Cloudflare Pages Functions. No Express, no long-running Node server.
- Database: Cloudflare D1. No Supabase.
- Auth: Web Crypto — PBKDF2 password hashing, HMAC-SHA256 session tokens. No bcrypt, no jsonwebtoken (native Node modules that do not run on Workers).
- No Node-only globals (process, Buffer) or native modules (better-sqlite3) in Worker/browser code.

## 7. Design requirements (verified by visual review, not code)

- Clean, modern, responsive, mobile-first. Sticky header with a wordmark/logo and cross-page nav. Organized, professional multi-column footer.
- Theme tokens only — no raw hex or px. WCAG AA contrast (4.5:1 text, 3:1 large/UI).
- No overlapping or clipped text at 375px. Verified at 375 / 768 / 1280.
- Every screen defines explicit loading, error, and empty states. Confirmation before destructive actions.
- Required pages: Home, About, Terms, Privacy, Contact. Full SEO (title/description/OG per route, sitemap, robots.txt).

## 8. Quality rules (RedAnvil rubric, tier-1 blockers)

- Strict typing, zero \`any\`. Smallest reviewable diff, no speculative abstraction.
- Fail closed with typed errors. Never log secrets or PII.
- Tests assert behavior. Parameterized SQL. Explicit timeouts. SAST clean.
- Frontend: pages compose named components; copy lives in a central locale bundle.

## 9. Test design

- Unit (Vitest): pure logic — validation, data transforms, the search filter.
- Component/browser (Playwright): the primary user flow end-to-end; loading/error/empty states.
- Accessibility (axe): zero serious/critical violations; contrast and heading order.
- Runtime parity: boot \`wrangler pages dev\` and curl a real endpoint before trusting green Node tests.

## 10. Effort estimate

- Estimated iterations to reach score 90: **${cost.iterations}**
- Approx. build tokens: **${cost.tokens.toLocaleString()}** (confidence: ${cost.confidence})

## 11. Scaffolding manifest

\`\`\`
src/
  main.tsx, App.tsx, theme.ts
  components/   Layout, ${entities[0] ?? 'Item'}List, ${entities[0] ?? 'Item'}Detail, states/
  pages/        Home, About, Terms, Privacy, Contact
  lib/          api client, validation (Zod schemas)
  i18n/         en.ts (all copy)
functions/
  api/          ${entities[0]?.toLowerCase() ?? 'items'}.ts, ${auth ? 'auth.ts, ' : ''}health.ts
wrangler.toml   D1 binding
\`\`\`

## 12. Initial build prompt (paste into the coder)

> Build the app in this PRD. Cloudflare Pages Functions + D1 + Web Crypto. Strict TypeScript, no \`any\`. Smallest correct diff. Follow every rule in sections 6–8. Ship the required pages with full SEO. Add unit + Playwright + axe tests. Do not stop until \`wrangler pages dev\` boots, the core flow works end-to-end, and the design passes a visual review at 375/768/1280. Target score: 90.
`;

  return { slug, title, prompt, markdown };
}
