import { readFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, it, expect } from 'vitest';
import { generatePrd } from './prd';
import { CASES, prdPayload, prdDigest } from '../../test-support/prdCharacterizationCases';

const fixturesDir = join(dirname(fileURLToPath(import.meta.url)), 'prd.characterization.fixtures');

/**
 * SHA-256 digests of JSON.stringify({slug,title,prompt,markdown}).
 *
 * Regenerated by `npx tsx scripts/regen-characterization.mts`, which runs the
 * real generator — never by hand. Last regenerated for Part A (az-planting-calendar):
 * entity derivation fail-closed (no Item), reference capability, prompt fidelity
 * §14 check, directive stripping, and product-title/slug derivation. Full golden
 * payloads live in `prd.characterization.fixtures/*.json`.
 */
const EXPECTED_DIGESTS: Readonly<Record<string, string>> = {
  'dashboard-auth-two-entities': '1a87c5eac6eb0ff9ade4cff38bcd1955b8305ced77746c314ee571882a4a2f66',
  'mobile-no-auth-two-entities': 'f1bd4a4b99b9de75500c68bb82243f82b428d52e40eb4cb038a0545aea975522',
  'marketplace-auth-scoped': 'bc437fcd4a4cce622eee585a72a9af35828744714981330b6bff9b7c459d479f',
  'empty-entities-no-auth': 'f91af7dbc69e333c743c8524e9433a640210982b96a3bf917290aff8dec171e5',
  'long-prompt-many-entities': 'e5e825f74eecc735a8dfcadba43a87de48c35457b06694a631cf580054046fbc'
};

describe('generatePrd characterization (byte-identical output)', () => {
  for (const c of CASES) {
    it(`matches golden output for ${c.id}`, () => {
      const prd = generatePrd(c.answers, c.cost);
      const payload = prdPayload(prd);
      const digest = prdDigest(prd);

      const fixturePath = join(fixturesDir, `${c.id}.json`);
      expect(existsSync(fixturePath), `missing fixture ${fixturePath}`).toBe(true);
      const golden = readFileSync(fixturePath, 'utf8');
      expect(payload).toBe(golden);
      expect(digest).toBe(EXPECTED_DIGESTS[c.id]);
    });
  }

  it('covers at least five varied inputs', () => {
    expect(CASES.length).toBeGreaterThanOrEqual(5);
    const ids = new Set(CASES.map((c) => c.id));
    expect(ids.size).toBe(CASES.length);
  });
});
