import { readFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, it, expect } from 'vitest';
import { generatePrd } from './prd';
import { CASES, prdPayload, prdDigest } from '../../test-support/prdCharacterizationCases';

const fixturesDir = join(dirname(fileURLToPath(import.meta.url)), 'prd.characterization.fixtures');

/**
 * SHA-256 digests of JSON.stringify({slug,title,prompt,markdown}).
 *
 * Regenerated by `npx tsx scripts/regen-characterization.mts`, which runs the
 * real generator — never by hand. Last regenerated when feature derivation began
 * reading the prompt, which changes every document that describes a real
 * capability — and deliberately leaves a plain CRUD prompt's digest unchanged.
 * Full golden payloads live in `prd.characterization.fixtures/*.json`.
 */
const EXPECTED_DIGESTS: Readonly<Record<string, string>> = {
  'dashboard-auth-two-entities': '3a549c7f6a280f2f70ec1d6cdf657d3ac0b032717b9f9b8b8448ddfc0d24306f',
  'mobile-no-auth-two-entities': 'bf6f317d25924f7a102590b32eea79f870a1aa8edb3de2e1fdc33d38dda6a275',
  'marketplace-auth-scoped': '0b6e72fd5899471c007982261fb8a7e2a0bc94ddb9b9bd730d163b2a0cb20df6',
  'empty-entities-no-auth': 'd2113c063577d14e9efdec6ebf36a94cd8604332d6d1d1fecfa384eeb5af6ba2',
  'long-prompt-many-entities': '2787f944a11f8f29166c16865b418bc64a4ce5a636c50a9a44544311dc443cf5'
};

describe('generatePrd characterization (byte-identical output)', () => {
  for (const c of CASES) {
    it(`matches golden output for ${c.id}`, () => {
      const prd = generatePrd(c.answers, c.cost);
      const payload = prdPayload(prd);
      const digest = prdDigest(prd);

      const fixturePath = join(fixturesDir, `${c.id}.json`);
      expect(existsSync(fixturePath), `missing fixture ${fixturePath}`).toBe(true);
      const golden = readFileSync(fixturePath, 'utf8');
      expect(payload).toBe(golden);
      expect(digest).toBe(EXPECTED_DIGESTS[c.id]);
    });
  }

  it('covers at least five varied inputs', () => {
    expect(CASES.length).toBeGreaterThanOrEqual(5);
    const ids = new Set(CASES.map((c) => c.id));
    expect(ids.size).toBe(CASES.length);
  });
});
